### ISSUE TITLE
Failed to make

### ISSUE THREAD

**Issue by Shaderboy** [muttleyxd/arma3-unix-launcher#100]
After running cmake successfully (I think), running make in the build directory gives me this:

`[  7%] Built target fmt
[ 10%] Building CXX object src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o
In file included from /home/chris/arma3-unix-launcher/src/common/filesystem_utils.cpp:1:0:
/home/chris/arma3-unix-launcher/src/common/filesystem_utils.hpp:3:22: fatal error: filesystem: No such file or directory
compilation terminated.
src/common/CMakeFiles/common.dir/build.make:95: recipe for target 'src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o' failed
make[2]: *** [src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o] Error 1
CMakeFiles/Makefile2:306: recipe for target 'src/common/CMakeFiles/common.dir/all' failed
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2`

Running Ubuntu 16.04

There are a couple of failures listed in the output from cmake, but I'm not sure if they matter:

`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/functions.cmake:116 (message):
  Warning: Applying workaround for GCC 8 and lower - linking stdc++fs
Call Stack (most recent call first):
  CMakeLists.txt:9 (add_libraries_to_linker)

-- Performing Test SYSTEM_argparse_WORKS
-- Performing Test SYSTEM_argparse_WORKS - Failed
-- Downloading argparse from https://github.com/p-ranav/argparse.git
-- Using external argparse
-- Performing Test SYSTEM_fmt_WORKS
-- Performing Test SYSTEM_fmt_WORKS - Failed
-- Downloading fmt from https://github.com/fmtlib/fmt.git
-- Version: 6.2.2
-- Build type: 
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Failed
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Failed
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Failed
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Failed
-- Required features: cxx_variadic_templates
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Using external fmt
-- Performing Test SYSTEM_pugixml_WORKS
-- Performing Test SYSTEM_pugixml_WORKS - Failed
-- Downloading pugixml from https://github.com/muttleyxd/pugixml.git
-- Using external pugixml
-- Performing Test SYSTEM_nlohmann_json_WORKS
-- Performing Test SYSTEM_nlohmann_json_WORKS - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chris/arma3-unix-launcher/build`

**Comment by muttleyxd** [comment]
C++17 compatible compiler is required - GCC 5.4.0 is too old, at least GCC 8 is required. If you can afford waiting for few days, I'll add Ubuntu 16.04 builds

**Comment by Shaderboy** [comment]
After installing GCC 9 via:

`sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9`

Running CMake no longer returns the same "Failed" tags, but make still returns the same errors afterwords.

**Comment by Shaderboy** [comment]
upgrading to gcc 8.4 verified gets me further, but ends with 

`[ 71%] Automatic MOC and UIC for target arma3-unix-launcher
AutoUic: /home/chris/arma3-unix-launcher/src/arma3-unix-launcher/mainwindow.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget1'.

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/arma3-unix-launcher/mainwindow.h"
into
  "SRC:/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/EWIEGA46WW/moc_mainwindow.cpp"

Command
-------
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -I/home/chris/arma3-unix-launcher/external/static-todo -I/home/chris/arma3-unix-launcher/src/arma3-unix-launcher-library -I/home/chris/arma3-unix-launcher/src/common -I/home/chris/arma3-unix-launcher/src/steam-integration -I/home/chris/arma3-unix-launcher/build/_deps/argparse-src/include -I/home/chris/arma3-unix-launcher/build/_deps/fmt-src/include -I/home/chris/arma3-unix-launcher/build/_deps/nlohmann_json-src/include -I/home/chris/arma3-unix-launcher/build/_deps/pugixml-src/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -o /home/chris/arma3-unix-launcher/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/EWIEGA46WW/moc_mainwindow.cpp /home/chris/arma3-unix-launcher/src/arma3-unix-launcher/mainwindow.h

Output
------
home/chris/arma3-unix-launcher/src/arma3-unix-launcher-library/arma3client.hp:9: Parse error at "ARMA3"

src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen.dir/build.make:77: recipe for target 'src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen' failed
make[2]: *** [src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen] Error 1
CMakeFiles/Makefile2:424: recipe for target 'src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen.dir/all' failed
make[1]: *** [src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by muttleyxd** [comment]
What Qt version do you have installed? Oldest I've tested was 5.9 from Ubuntu 18.04

**Comment by Shaderboy** [comment]
`qmake -v` outputs
`QMake version 3.1
Using Qt version 5.14.2 in /home/chris/Qt/5.14.2/gcc_64/lib`

**Comment by muttleyxd** [comment]
Try deleting build folder (to clear existing CMake cache) and run
```
cmake .. -DCMAKE_PREFIX_PATH=$(dirname $(which qmake))/..
```

This is a hack, but it'll try to obtain Qt5 install directory based on where qmake is installed. I hope it works, if it doesn't then I'll test it myself, but now I don't have access to Ubuntu 16.04 machine.

**Comment by Shaderboy** [comment]
So I tried running

`cmake .. -DCMAKE_PREFIX_PATH=$(~/Qt $(which qmake))/..`

and got the same result. I might be misunderstanding exactly what the command is though?

**Comment by Shaderboy** [comment]
Trying to run the binary gave me these errors:

`arma3-unix-launcher: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by arma3-unix-launcher)
arma3-unix-launcher: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by arma3-unix-launcher)
arma3-unix-launcher: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by arma3-unix-launcher)
arma3-unix-launcher: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by arma3-unix-launcher)`

Explicitly setting the path to the Qt lib made it work:

`export LD_LIBRARY_PATH=~/Qt/5.14.2/gcc_64/lib:$LD_LIBRARY_PATH`

Now the binary runs with this error: 

`conf file: "/home/chris/.config/a3unixlauncher/launcher.conf"
cannot read config file: [json.exception.out_of_range.403] key 'paths' not found
Install path: "/home/chris/.local/share/Steam"
[S_API] SteamAPI_Init(): Loaded '/home/chris/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197991292793 [API loaded no]`

And attempting to clean and build with the command in the last post has a different output, though it still fails:

`AutoUic subprocess error
------------------------
The uic process failed to compile
  "SRC:/src/arma3-unix-launcher/mainwindow.ui"
into
  "SRC:/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/include/ui_mainwindow.h"
included by
  "SRC:/src/arma3-unix-launcher/mainwindow.cpp"
  "SRC:/src/arma3-unix-launcher/settings.cpp"

Command
-------
/usr/lib/x86_64-linux-gnu/qt5/bin/uic -o /home/chris/arma3-unix-launcher/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/include/ui_mainwindow.h /home/chris/arma3-unix-launcher/src/arma3-unix-launcher/mainwindow.ui

Output
------
/usr/lib/x86_64-linux-gnu/qt5/bin/uic: symbol lookup error: /usr/lib/x86_64-linux-gnu/qt5/bin/uic: undefined symbol: qt_qhash_seed


AutoUic subprocess error
------------------------
The uic process failed to compile
  "SRC:/src/arma3-unix-launcher/arma_path_chooser_dialog.ui"
into
  "SRC:/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/include/ui_arma_path_chooser_dialog.h"
included by
  "SRC:/src/arma3-unix-launcher/arma_path_chooser_dialog.cpp"

Command
-------
/usr/lib/x86_64-linux-gnu/qt5/bin/uic -o /home/chris/arma3-unix-launcher/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/include/ui_arma_path_chooser_dialog.h /home/chris/arma3-unix-launcher/src/arma3-unix-launcher/arma_path_chooser_dialog.ui

Output
------
/usr/lib/x86_64-linux-gnu/qt5/bin/uic: symbol lookup error: /usr/lib/x86_64-linux-gnu/qt5/bin/uic: undefined symbol: qt_qhash_seed


AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/arma3-unix-launcher/mainwindow.h"
into
  "SRC:/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/EWIEGA46WW/moc_mainwindow.cpp"

Command
-------
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -I/home/chris/arma3-unix-launcher/external/static-todo -I/home/chris/arma3-unix-launcher/src/arma3-unix-launcher-library -I/home/chris/arma3-unix-launcher/src/common -I/home/chris/arma3-unix-launcher/src/steam-integration -I/home/chris/arma3-unix-launcher/build/_deps/argparse-src/include -I/home/chris/arma3-unix-launcher/build/_deps/fmt-src/include -I/home/chris/arma3-unix-launcher/build/_deps/nlohmann_json-src/include -I/home/chris/arma3-unix-launcher/build/_deps/pugixml-src/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -o /home/chris/arma3-unix-launcher/build/src/arma3-unix-launcher/arma3-unix-launcher_autogen/EWIEGA46WW/moc_mainwindow.cpp /home/chris/arma3-unix-launcher/src/arma3-unix-launcher/mainwindow.h

Output
------
home/chris/arma3-unix-launcher/src/arma3-unix-launcher-library/arma3client.hp:9: Parse error at "ARMA3"

src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen.dir/build.make:77: recipe for target 'src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen' failed
make[2]: *** [src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen] Error 1
CMakeFiles/Makefile2:424: recipe for target 'src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen.dir/all' failed
make[1]: *** [src/arma3-unix-launcher/CMakeFiles/arma3-unix-launcher_autogen.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by muttleyxd** [comment]
```
conf file: "/home/chris/.config/a3unixlauncher/launcher.conf" 
[S_API] SteamAPI_Init(): Loaded '/home/chris/.local/share/Steam/linux64/steamclient.so' OK. Setting breakpad minidump AppID = 107410 SteamInternal_SetMinidumpSteamID: Caching Steam ID: 76561197991292793 [API loaded no] 
Running Arma: env SteamGameId=107410 LD_PRELOAD=/home/chris/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so STEAM_COMPAT_DATA_PATH="/home/chris/.local/share/Steam/steamapps/compatdata/107410" "/home/chris/.local/share/Steam/steamapps/common/Proton 4.11/proton" run "/home/chris/.local/share/Steam/steamapps/common/Arma 3/arma3_x64.exe" -noSplash -skipIntro
ERROR: ld.so: object '/home/chris/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored. 
ERROR: ld.so: object '/home/chris/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored. 
esync: up and running. 
Setting breakpad minidump AppID = 107410 
Steam_SetMinidumpSteamID: Caching Steam ID: 76561197991292793 [API loaded no]
```

this output looks fine, is the game starting? (ld.so errors are normal, as there some 32-bit binaries on the A3UL-Steam-Arma line)

Anyways, I'm working on adding Ubuntu 16.04 builds to CI/CD builds

**Comment by muttleyxd** [comment]
@Shaderboy 
I've uploaded early version I have built on my PC using Docker, looks fine to me, I'd be happy if you could test it.
https://github.com/muttleyxd/arma3-unix-launcher/releases/tag/deb-docker-build

It'll install launcher to `/opt/arma3-unix-launcher`, alongside with Qt 5.14.2 libraries in `/opt/arma3-unix-launcher/lib` and `/usr/bin/arma3-unix-launcher` script.

If it installs fine, then you should be able to launch it simply with `arma3-unix-launcher` command

**Comment by Shaderboy** [comment]
Thanks for the quick responses. Still no go sadly. Installing that launches the launcher but still gives issues when trying to launch the game itself. It does launch Steam and start the launch process from there. But the game won't launch from steam itself with or without this launcher, so it's possible the issue is just out of the scope of this project.

**Comment by muttleyxd** [comment]
> But the game won't launch from steam itself with or without this launcher, so it's possible the issue is just out of the scope of this project.

Probably, I'd try running Steam and seeing if there's something about it in logs (maybe some libraries missing?).

**Comment by muttleyxd** [comment]
Since Arma doesn't run for you without the launcher, there isn't much I can do. I think I can close this issue, also I've added Ubuntu 16.04 package to releases.

Feel free to reopen if you need to.
