### ISSUE TITLE
feature request: add Fedora 32 (and earlier?)/AppImage/Flatpak builds

### ISSUE THREAD

**Issue by muttleyxd** [muttleyxd/arma3-unix-launcher#107]

**Comment by Holsterbau** [comment]
That would be nice. There's a lot of Fedora gamers out there.

**Comment by Hubok** [comment]
I'm on Fedora 32 as well, and we don't always need something in RPM form. Providing it as an AppImage or an easy install script is also fine.

**Comment by muttleyxd** [comment]
I went for AppImage approach, but for now `linuxdeploy` with their Qt plugin seems broken.

For now this is blocked by:
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/72

**Comment by muttleyxd** [comment]
Added AppImage build, currently lacking desktop integration and theming support.

Feel free to reopen if issue persists.
