### ISSUE TITLE
feature request: Export Workshop Mods list Human readable

### ISSUE THREAD

**Issue by ninelore** [muttleyxd/arma3-unix-launcher#108]
...with the Full Name and Workshop link included

**Comment by muttleyxd** [comment]
Please check if newest release works fine
https://github.com/muttleyxd/arma3-unix-launcher/releases/tag/commit-217

**Comment by muttleyxd** [comment]
Finally I found some time to fix this properly - now names are taken from "Name" field in Workshop mods table.
