### ISSUE TITLE
Valgrind Reports Memory Leak

### ISSUE THREAD

**Issue by CAPTNCAPS** [muttleyxd/arma3-unix-launcher#11]
I just let the valgrind run the program and sadly found that it reports memory leaks. I do not yet know if this is a problem with the program, or Gtk.
I will investigate this further and try to fix the these memory leaks where possible.
Creating this issue simply as information / a reminder.

**Comment by CAPTNCAPS** [comment]
It seems that at least partly Gtk is at fault, as no program files but only libraries are mentioned in some stacktraces.
The `Dirty fix to Gtk::Application trying to parse arguments on its own` also seems to cause some kind of memory leak in Gtk. At least main.cpp:98 is mentioned time and time again in Valgrinds logs.
Lastly, from what I found so far, Utils::Split() caused a memory leak as `char *text = new[]` was never `delete[]`ed. This is fixed in #12

**Comment by muttleyxd** [comment]
Will look into it in few days

**Comment by muttleyxd** [comment]
This was fixed some time ago. Closing.
