### ISSUE TITLE
Manjaro says missing library, should be installed already?

### ISSUE THREAD

**Issue by mxKaZVN** [muttleyxd/arma3-unix-launcher#121]
"arma3-unix-launcher: error while loading shared libraries: libfmt.so.6: cannot open shared object file: No such file or directory"

I have the "fmt" package installed already, 7.0.3-1. Could you say if it is something from manjaro that I might be missing? Looking forward to playing online again now that it matches server versions.

**Comment by muttleyxd** [comment]
Fixed by #122.

Feel free to reopen if issue persists.
