### ISSUE TITLE
crash: missing support for Steam running in Flatpak

### ISSUE THREAD

**Issue by tosyu** [muttleyxd/arma3-unix-launcher#124]
Hello

I have a problem with the launcher, it crashes after startup

```
Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

Steam is running under flatpak, and Arma 3 is running through Proton, but I did not manage to start it through arma3-unix-launcher, because the launcher crashes (the game works fine when started with steam)

and the log file
```
conf file: "/home/tosyu/.config/a3unixlauncher/launcher.conf"
Icon theme "Numix-Circle" not found.
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Loaded '/home/tosyu/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198175095966 [API loaded no]
exception while parsing settings["protonDisableEsync"]:
[json.exception.out_of_range.403] key 'protonDisableEsync' not found
CCrossProcessPipe::BWrite wrote too few bytes: 32 (Przerwany potok).  Continuing.
/data/src/common/pipes.cpp (572) : Assertion Failed: m_pInternalPipe->BRead failed
/data/src/common/pipes.cpp (572) : Assertion Failed: m_pInternalPipe->BRead failed
/data/src/common/processpipe_posix.cpp (507) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Przerwany potok)
/data/src/common/processpipe_posix.cpp (507) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Przerwany potok)
/data/src/common/pipes.cpp (750) : CClientPipe::BWriteAndReadResult: BWrite failed
/data/src/common/pipes.cpp (750) : CClientPipe::BWriteAndReadResult: BWrite failed
assert_20200825023951_2.dmp[20984]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200825023951_2.dmp
/data/src/common/pipes.cpp (750) : Fatal assert failed: /data/src/common/pipes.cpp, line 750.  Application exiting.

/data/src/common/pipes.cpp (750) : Fatal assert failed: /data/src/common/pipes.cpp, line 750.  Application exiting.

assert_20200825023951_2.dmp[20984]: Finished uploading minidump (out-of-process): success = no
assert_20200825023951_2.dmp[20984]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20200825023951_2.dmp[20984]: file ''/tmp/dumps/assert_20200825023951_2.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
_ExitOnFatalAssert
assert_20200825023951_4.dmp[20987]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200825023951_4.dmp
assert_20200825023951_4.dmp[20987]: Finished uploading minidump (out-of-process): success = no
assert_20200825023951_4.dmp[20987]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20200825023951_4.dmp[20987]: file ''/tmp/dumps/assert_20200825023951_4.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
```

Is there something I can do to resolve this issue?

The launcher would be helpful with managing mods (right now I'm appending them to arma3 startup options which is cumbersome)

**Comment by muttleyxd** [comment]
Hey,

Steamworks initialization seems to fail, later it reports that `libcurl.so`  is missing, so please try installing `libcurl4` and `libcurl4-openssl-dev`

```
sudo apt update && sudo apt install libcurl4 libcurl4-openssl-dev
```

Also you can try building the launcher from source, without Steamworks integration

```
git clone https://github.com/muttleyxd/arma3-unix-launcher.git
cd arma3-unix-launcher
mkdir build
cd build
cmake ..
make -j4
```
and run it with
```
./src/arma3-unix-launcher/arma3-unix-launcher
```

**Comment by muttleyxd** [comment]
I just noticed that you're running Steam with Flatpak, that may be a problem - building from source may help here a little, as it shouldn't crash and after manually specifying, where Arma is installed, it should work fine.

Just watch out, that you won't have an ability to subscribe to mods, when importing HTML mod presets.

**Comment by tosyu** [comment]
Hmm I cannot compile the code right now as cmake when starting needs gcc-8-multilib installed and I have few packages from unstable which prevent me from installing it (unmet deps). I need to fix my instalation :)

So if you are sure that the crash is the fault of my setup (flatpak), then feel free to close the issue.

**Comment by muttleyxd** [comment]
I didn't have time recently, so sorry for late response.

> So if you are sure that the crash is the fault of my setup (flatpak)

![well yes but actually no](https://wompampsupport.azureedge.net/fetchimage?siteId=7575&v=2&jpgQuality=100&width=700&url=https%3A%2F%2Fi.kym-cdn.com%2Fentries%2Ficons%2Ffacebook%2F000%2F028%2F596%2FdsmGaKWMeHXe9QuJtq_ys30PNfTGnMsRuHuo_MUzGCg.jpg)

I think I'll try to add support for running Steam in Flatpak (somewhat) soon, as the launcher should be able to find Arma inside Flatpak.

**Comment by tosyu** [comment]
Ok, thanks for the explanation. 

FIY I have resolved my problem my os packages and reinstalled steam without flatpak, works flawlessly

**Comment by muttleyxd** [comment]
This has been fixed. Steam integration will be missing, but that's not something I can easily fix - as steam_api.so just crashes when trying to interact with Steam inside Flatpak.

Feel free to reopen if issue persists.
