### ISSUE TITLE
Launcher doesn't run arma 3 with the steam-runtime

### ISSUE THREAD

**Issue by VurtualRuler98** [muttleyxd/arma3-unix-launcher#126]
Background: While trying to diagnose an issue with thermal vision not working, I tried running arma 3 from steam without the launcher, and thermal vision worked fine. I then tried manually running arma 3 with the launcher open, using the same command invocation method it does in arma's directory, and thermal vision was still broken. Adding PROTON_LOG=1 I noticed some libpng12 errors with the launcher's method vs running with steam directly. libpng12 isn't shipped with the distro I use (debian 10), but is included in the steam runtime. Going from THIS:

`env SteamGameId=107410 PROTON_LOG=1 LD_PRELOAD=/home/vurtual/.steam/steam/ubuntu12_64/gameoverlayrenderer.so STEAM_COMPAT_DATA_PATH="/bigssd/vurtual/steam/steamapps/compatdata/107410"  "/bigssd/vurtual/steam/steamapps/common/Proton 5.0/proton" run "/bigssd/vurtual/steam/steamapps/common/Arma 3/arma3_x64.exe" -noLauncher`

to THIS:

`env SteamGameId=107410 PROTON_LOG=1 LD_PRELOAD=/home/vurtual/.steam/steam/ubuntu12_64/gameoverlayrenderer.so STEAM_COMPAT_DATA_PATH="/bigssd/vurtual/steam/steamapps/compatdata/107410" "/home/vurtual/.steam/root/ubuntu12_32/steam-runtime/run.sh" "/bigssd/vurtual/steam/steamapps/common/Proton 5.0/proton" run "/bigssd/vurtual/steam/steamapps/common/Arma 3/arma3_x64.exe" -noLauncher`

adding `"/home/vurtual/.steam/root/ubuntu12_32/steam-runtime/run.sh"` as the initial command to run fixed the issue entirely.

I'm not sure how detecting whether steam wants to use the runtime or not would work(steam-runtime vs steam-native or STEAM_RUNTIME=1 set, etc), but if nothing else can we get a checkbox option to enable it?

**Comment by muttleyxd** [comment]
Fixed by #128 

launcher will now detect if `libpng12.so` is present, if it is, then it'll start the game normally, if not, then it'll start the game with steam-runtime.

Also I could implement a GUI setting for this, but I went for the quicker one :grin:

Feel free to reopen if issue persists.
