### ISSUE TITLE
Can someone teach me how to run this launcher, please?

### ISSUE THREAD

**Issue by NightHunter3007** [muttleyxd/arma3-unix-launcher#129]
https://drive.google.com/file/d/1OErTHJQeEFYSZXdfCrd__j2bIq3KqQav/view

This is a screen video, I conducted this process, but can not use and see the mods.

Any idea?

Mac:
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Intel Iris Plus Graphics 640 1536 MB

**Comment by ShaunTheQuietGamer** [comment]
https://www.youtube.com/watch?v=swJPic2eKGA

**Comment by muttleyxd** [comment]
Sorry for late response, but I don't have access to the video

**Comment by muttleyxd** [comment]
Didn't get any response for a month, still no access to the link. Closing as stale.

Feel free to reopen if you have any updates.
