### ISSUE TITLE
Proton 5.13 "Need a Verb"

### ISSUE THREAD

**Issue by Sora012** [muttleyxd/arma3-unix-launcher#134]
If you set Arma 3 to use Proton 5.13 and try to launch through the Arma3 Unix Launcher it will not launch the game, and say "Proton: Need a Verb"

> [sora@Sora-PC ~]$ arma3-unix-launcher 
conf file: "/home/sora/.config/a3unixlauncher/launcher.conf"
[S_API] SteamAPI_Init(): Loaded '/home/sora/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197996829374 [API loaded no]
Running Arma:
env  SteamGameId=107410 LD_PRELOAD=/home/sora/.steam/steam/ubuntu12_64/gameoverlayrenderer.so STEAM_COMPAT_DATA_PATH="/mnt/Data/SteamLibrary/steamapps/compatdata/107410"  "/home/sora/.steam/steam/steamapps/common/Proton 5.13/proton" %verb% "/mnt/Data/SteamLibrary/steamapps/common/Arma 3/arma3_x64.exe"  -enableHT -exThreads=7 -noLogs -noSplash -skipIntro
Proton: Upgrading prefix from 5.0-1 to 5.13-1 (/mnt/Data/SteamLibrary/steamapps/compatdata/107410/)
Proton: Need a verb.

**Comment by muttleyxd** [comment]
Fixed by 918efff38218968fa1e2dad940efdc23ca91cdba

Feel free to reopen if issue persists.
