### ISSUE TITLE
Program doesn't find the game

### ISSUE THREAD

**Issue by fedebenelli** [muttleyxd/arma3-unix-launcher#135]
Hello, I've tried with both the AUR version and the AppImage, whenever I try to run it it returns:

```
$ arma3-unix-launcher -v
conf file: "/home/ruther/.config/a3unixlauncher/launcher.conf"
cannot read config file: [json.exception.out_of_range.403] key 'paths' not found
Install path: "/home/ruther/.local/share/Steam"
Didn't find game at "/home/ruther/.local/share/Steam"
Error: map::at
Install path: "/media/fafb/games/steamgaems"
Didn't find game at "/media/fafb/games/steamgaems"
Error: map::at
Install path: "/media/bigdata/games/steamgaems"
Didn't find game at "/media/bigdata/games/steamgaems"
Error: Steam Workshop directory not found for appid: 107410
```
Just in case, the install dir is "/media/bigdata/games/steamgaems/steamapps/common/Arma 3/", on an NTFS partition

**Comment by muttleyxd** [comment]
Does this window appear for you? You should be able to click Browse and select the game path from there

![arma 3 path chooser dialog](https://i.imgur.com/HRMapMn.png)

**Comment by fedebenelli** [comment]
It fixed itself once I subscribed to some random workshop item!
(Before that the GUI window appeared just a horizontal line of ~1 pixel height)

**Comment by muttleyxd** [comment]
> (Before that the GUI window appeared just a horizontal line of ~1 pixel height)

This shouldn't happen, what DE/WM do you use?

**Comment by fedebenelli** [comment]
I'm using dwm, later when on my machine I'll give it a try on i3-gaps (I'm on a messy Arch build, so maybe that problem is related to some config of mine)

**Comment by muttleyxd** [comment]
I made a stupid mistake in dialog's code - it was trying to set the maximum height to 1 pixel. Most DE/WMs didn't respect that, but dwm behaves correctly here and does this. Fixed.

Feel free to reopen it if issue persists.
