### ISSUE TITLE
on Linux mint 

### ISSUE THREAD

**Issue by GhChancellor** [muttleyxd/arma3-unix-launcher#14]
Hello Muttleyxd,

on mint 17.3 it doesn't work I tried 
with arma3-unix-launcher_master-44-4bb538e-debian-x86_64.deb

> "arma3-unix-launcher [2017-11-25 17:59:58] ArmA 3 Unix Launcher started
> [2017-11-25 17:59:58] Can't open /home/lele/.local/share/Steam/config/config.vdf
> Critical error
> 
> [2017-11-25 17:59:58] Can't open /home/lele/.local/share/Steam/config/config.vdf
> Critical error
> 
> arma3-unix-launcher: symbol lookup error: arma3-unix-launcher: undefined symbol: _ZN3Gtk7Builder16create_from_fileERKSs "

with arma3-unix-launcher_master-44-4bb538e-ubuntu-x86_64.deb

> arma3-unix-launcher arma3-unix-launcher: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by arma3-unix-launcher

bye
Lele

**Comment by muttleyxd** [comment]
Hey,

could you try building from source?

```
git clone https://github.com/muttleyxd/arma3-unix-launcher.git
cd arma3-unix-launcher
mkdir build
cd build
cmake ..
make
./arma3-unix-launcher
```

It looks like it's linked against incorrect version (as I have noticed, Mint is based on Ubuntu 14.04, and oldest version I tested was Ubuntu 16.04, so there might be a problem there).

Unfortunately next few weeks will be kind of busy for me, so I'm not sure if I'll find enough time to fire up Mint VM and see myself if there is a problem.

**Comment by GhChancellor** [comment]
Hello

i formatting my pc, i tried to compile and seem it's work. But before i must re-install arma, give me some days and a will write you.

thank you

**Comment by muttleyxd** [comment]
>  i tried to compile and seem it's work

So it looks like deb packages are linked against incorrect version. So for now you should stick with self-compiling, as I've mentioned before - next few weeks I probably won't find any time to solve this issue.

**Comment by GhChancellor** [comment]
Hello Muttley,

i confirm, after compile your program work on mint 18.3

thank you for your support

Bye

Lele
