### ISSUE TITLE
Add ability to export mod presets as Arma Launcher html Preset

### ISSUE THREAD

**Issue by royalmustard** [muttleyxd/arma3-unix-launcher#140]
Right now, the modlist can only be exported as json, which cannot be imported into the normal arma launcher. This feature would enable users to share presets on multiple os.

**Comment by VurtualRuler98** [comment]
I made a very barebones shell script that smooshes together the right html to do this, it's not really worth basing anything off of but it works enough until actual support for this is added.

https://github.com/VurtualRuler98/arma3-preset-script

**Comment by muttleyxd** [comment]
Closed by #149

Feel free to reopen if issue persists.
