### ISSUE TITLE
Add update information into AppImage

### ISSUE THREAD

**Issue by soulflyman** [muttleyxd/arma3-unix-launcher#151]
It would be nice if you could provide update information in the AppImage itself.
So it would be easy to update to a newer version and it would much better integrate when using [appimaged](https://github.com/probonopd/go-appimage) and [appimageupdater](https://github.com/antony-jr/AppImageUpdater).

https://appimage-builder.readthedocs.io/en/latest/advanced/updates.html#setting-appimage-update-information

**Comment by muttleyxd** [comment]
I added update notifier for all available releases, feel free to reopen if it doesn't work
