### ISSUE TITLE
"Invalid env format" with flatpak Steam - Manjaro 20.2.1

### ISSUE THREAD

**Issue by CryptArma** [muttleyxd/arma3-unix-launcher#154]
Hi, sorry for my english, I am using Manjaro 20.2.1 with Steam/Proton in flatpak and no DLC and apparently the error "Invalid env format" is being caused by "protonDisableEsync" in the launcher config (/home/user/.config/a3unixlauncher/launcher.conf) having "false" as the value but when you change for "true" (or use the option in the launcher to disable) it will work fine. Thank you for you patience and hard work. (Btw this is related with issue #152).

**Comment by muttleyxd** [comment]
This should be fixed by 164bf27 and #207.

Feel free to reopen if issue persists.
