### ISSUE TITLE
Wrong mod name making game unable to launch

### ISSUE THREAD

**Issue by Clemenk** [muttleyxd/arma3-unix-launcher#156]
Hi,

I downloaded this mod : https://steamcommunity.com/sharedfiles/filedetails/?id=867431642&searchtext=I44
And the mod name appears like that: 
![image](https://user-images.githubusercontent.com/69971519/114019444-b4ad1a80-986e-11eb-8c1a-846cf583ca9a.png)
When I first launch the game with the mod selected I get this error:
![image](https://user-images.githubusercontent.com/69971519/114021439-fccd3c80-9870-11eb-9dac-d02a9d606f97.png)
And after that I always get this one:
![image](https://user-images.githubusercontent.com/69971519/114021590-25553680-9871-11eb-9d12-f6e1d6ff30cf.png)

In `~/.local/.config/a3unixlauncher/launcher.cfg` it appears like that:
```
        {
            "enabled": false,
            "name": "\"Invasion1944Terrains",
            "path": "867431642"
        }
```

I found that in this file: `~/.local/share/Steam/steamapps/compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/Arma3.cfg` there is an added quote:
```
class ModLauncherList
{
    class Mod1
    {
        dir="867431642";
        name=""Invasion1944Terrains";
        origin="GAME DIR";
        fullPath="Z:\home\clement\.local\share\Steam\steamapps\workshop\content\107410\867431642";
    };
};

``` 
And if I delete this quote the game starts properly at the only condition that I launch it through steam with the -nolauncher option. But if I launch it through the unix launcher the quote appears once again.

I have a friend who downloaded the same mod and in his case the name of the mod is: `I44_Terrains` and he has no problem.

My guess is that in my case a3unixlauncher takes the name from the mod.cpp file and not from the meta.cpp file since the name in meta.cpp is `I44_Terrains` and the name in mod.cpp is `Invasion 1944 Terrains`, but this is weird because we both installed the same package, namely arma3-unix-launcher-bin. Or there is a formatting issue when ModLauncherList is generated.

**Comment by muttleyxd** [comment]
I have implement a workaround for this - quotes will be replaced by underscores. 

Feel free to reopen if issue persists.

**Comment by Clemenk** [comment]
It's working again, thanks a lot!
