### ISSUE TITLE
Launcher looking for Steam workshop mods in the wrong location

### ISSUE THREAD

**Issue by ademptis112** [muttleyxd/arma3-unix-launcher#16]
The launcher did not detect mods installed by the Steam workshop. This is because it looks for workshop mods in `/home/$USER/workshop/content/107410`, while Steam installs them to `/home/$USER/.local/share/Steam/steamapps/workshop/content/107410/`. I tried changing this in the launcher config file (`/home/$USER/.config/a3unixlauncher/settings.conf`), but this is reverted when I then open the launcher.
My workaround for this issue was `ln -s /home/$USER/.local/share/Steam/steamapps/workshop/ /home/$USER/workshop`

**Comment by muttleyxd** [comment]
Okay, that's weird. It looks like sometimes it incorrectly evaluates mod install path. It will be fixed in new rewritten version, also I'll give an option to manually set paths from options

**Comment by ademptis112** [comment]
Ah, I see. If I may ask, when do you expect the new launcher to be available?

**Comment by muttleyxd** [comment]
It's not coming fast, I have to travel a lot now unfortunately. 

I think maybe I should look into hotfixing this issue, because I might not make it in April.

**Comment by muttleyxd** [comment]
@ademptis112 Would you give me output arma3-unix-launcher creates?
You would need to open up the terminal and run
```
arma3-unix-launcher --purge
arma3-unix-launcher --verbose >launcher.log
```

and then paste here content of launcher.log file after it launches and then you can close it.

Also please mind that
`arma3-unix-launcher --purge`
will remove your configuration files (they are stored in ~/.config/a3unixlauncher, so if you want to keep your settings you should backup it first).

**Comment by ademptis112** [comment]
Here is the launcher.log with the symlink I created in place. My mods appear in the launcher in this case. [launcher.log](https://github.com/muttleyxd/arma3-unix-launcher/files/1844704/launcher.log)
And here is the launcher.log without the symlink. Workshop mods did not appear. [launcher.log](https://github.com/muttleyxd/arma3-unix-launcher/files/1844705/launcher.log)
In both cases, it asked me to select Arma's install directory.

**Comment by muttleyxd** [comment]
Okay, may I ask how did you make it that Steam installs games in ~/steam-games?
Or is it a symlink too?

When I create a Steam library it creates directories like that
```
/mnt/games/SteamLibrary/common/Arma 3
/mnt/games/SteamLibrary/workshop/107410
```

Based on this I made an assumption that removing 2 directories (common/Arma 3 in this case) and adding 'workshop/content/107410' to it will point to workshop directory.

Anyways I pushed a new branch with possibly working hotfix to this - it's called 'fix-missing-workshop'.
```
git clone https://github.com/muttleyxd/arma3-unix-launcher.git
cd arma3-unix-launcher
git checkout fix-missing-workshop
mkdir build
cd build
cmake ..
make
./arma3-unix-launcher --purge
./arma3-unix-launcher --verbose >launcher.log
```

So please check if this attempt does work

**Comment by ademptis112** [comment]
Sorry, I should have said this before. `~/steam-games` is a symlink to `~/.local/share/Steam/steamapps/common`. I made it so that I could access game folders easier.
I tried tried the new branch, but it doesn't seem to detect workshop mods at all, even with the `~/workshop` symlink workaround.

**Comment by muttleyxd** [comment]
Okay, I'll try to add some code resolving symlinks, which should help in this case, but I'm going to do it tommorrow

**Comment by ademptis112** [comment]
Alright, thank you.

**Comment by muttleyxd** [comment]
Next try - there was a bug in a function looking for steam library - it didn't look into ~/.local/share/Steam/steamapps/common for games :cry: 

Anyways, please see if new version works
```
cd <arma3-unix-launcher location>
cd build
git fetch origin
git pull
make
./arma3-unix-launcher --purge
./arma3-unix-launcher --verbose >launcher.log
```

**Comment by ademptis112** [comment]
This version seems to work. I removed my workshop symlink, and it still found the location of workshop mods. It asked me to locate Arma's install directory, though.

**Comment by muttleyxd** [comment]
I guess it'll have to do then, I'm merging this with master

I'm back to working on rewritten version (with proper unit-testing which should avoid me bugs like that one)

**Comment by ademptis112** [comment]
Yeah, it's not a huge inconvenience having to locate it the once.
I look forward to using the new launcher.
