### ISSUE TITLE
Arma 3 not launching after loading

### ISSUE THREAD

**Issue by Sacha-Ringenbach** [muttleyxd/arma3-unix-launcher#162]
I'm not sure if this an issue with the launcher or proton.

I've tried several versions of proton, from the newest to 4.29, nothing seems to work.

[Report.txt](https://github.com/muttleyxd/arma3-unix-launcher/files/6565401/Report.txt)

Running 5.12.8-arch1-1

```
[Radeon RX 470/480/570/570X/580/580X/590] (rev ef) (prog-if 00 [VGA controller])
	Subsystem: Sapphire Technology Limited Nitro+ Radeon RX 570/580/590
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

**Comment by muttleyxd** [comment]
Hi,

probably it's not launcher issue, but here's what you can do to confirm it:
```
find / -name Arma3.cfg
```
this should find Arma3.cfg, you should delete this file (just check if it's the correct one) - it's the only file that launcher modifies and it may impact Arma's behavior. After you delete it go into Steam, edit Arma 3 launch parameters and set them to `-nolauncher`.

Then you can start the game simply from Steam client by pressing "Play" - if it doesn't work, then it definitely isn't launcher issue.
