### ISSUE TITLE
Direct launch failed, exception: compatibility tool entry not found

### ISSUE THREAD

**Issue by MBR-0001** [muttleyxd/arma3-unix-launcher#168]
This occurs every time I try to launch the game using the launcher, the game starts fine through steam

## Console Output
```
conf file: "/home/mbr/.config/a3unixlauncher/launcher.conf"
[S_API] SteamAPI_Init(): Loaded '/home/mbr/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198089xxxxxx [API loaded no]
Direct launch failed, exception: compatibility tool entry not found
```

Arch linux, obtained from [AUR](https://aur.archlinux.org/packages/arma3-unix-launcher-bin/)

I looked at the code and from what I saw it tries to obtain version of proton the game uses from `config.vdf`, I checked the file (`/home/mbr/.steam/steam/config/config.vdf`) and the version is there
![](https://cdn.mbr.pw/54530051194093586.png)
I also compiled the launcher (to add logging) but none of the steam stuff gets logged to console (just the first conf file line)

**Comment by Spartan322** [comment]
It seems the problem has to do with the launcher looking only in the default folder since it relies on `"BaseInstallFolder"` in the `config.vdf`, if it can't find it any relevant files there it doesn't recognize the install, issue is that isn't where the other folder information is stored, instead you most look in `config/libraryfolders.vdf` which also stores the games making it also fairly easy to figure out 1) if the game is installed and 2) where the game is installed all without searching everywhere for it.

**Comment by MBR-0001** [comment]
I just checked, there is no `"BaseInstallFolder"` in config.vdf, there's `"BaseInstallFolder_1"` and `"BaseInstallFolder_2"` tho, is it possible that steam changed this?

**Comment by Spartan322** [comment]
`BaseInstallFolder_1` and `BaseInstallFolder_2` I suspect are one of the weird value list forms that can be taken which in this tool seem to parsed correctly, however its not guaranteed that any of your library files will reside in those directories.

**Comment by muttleyxd** [comment]
I refactored how compatibility tools are found, so this issue was possibly fixed. Please test this release https://github.com/muttleyxd/arma3-unix-launcher/releases/tag/commit-303

**Comment by Spartan322** [comment]
I can personally (@MBR-0001 can you?) confirm the commit 303 release fixes this issue and enables the game to start properly on a secondary steam library path not listed in the config file. (reinforced by examining the change to the source that corrects the reference to use `libraryfolder.vdf`) I tested on the AUR package. Offtopic note @muttleyxd, the AUR package relies on spdlog being installed it seems but does not have a dependency on it, I incidentally didn't have it installed, perhaps it should be added as a dependency.

**Comment by muttleyxd** [comment]
> Offtopic note @muttleyxd, the AUR package relies on spdlog being installed it seems but does not have a dependency on it, I incidentally didn't have it installed, perhaps it should be added as a dependency.

Fixed! Thanks for noticing this!

**Comment by MBR-0001** [comment]
I just tried the latest verison and the issue is fixed, thanks!

**Comment by k1ll1n** [comment]
Hello!
Now I have the same error when running "DayZ"
![image](https://user-images.githubusercontent.com/4102348/187090558-8cc2b68f-815f-439d-9ac9-2b2d18da5ecd.png)
