### ISSUE TITLE
Install from source compilation terminated. 

### ISSUE THREAD

**Issue by witcherenjoyer** [muttleyxd/arma3-unix-launcher#170]
This is my first time installing something this way, so bear with me. 

I am running opensuse leap 15.3 and gcc 7.5

When I make in the directory, i get this output:
[  2%] Building CXX object src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o
In file included from /home/tom/.steam/arma3unixlauncher/arma3-unix-launcher/src/common/filesystem_utils.cpp:1:0:
/home/tom/.steam/arma3unixlauncher/arma3-unix-launcher/src/common/filesystem_utils.hpp:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:93: src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:325: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:147: all] Error 2

I am assuming this error is due to gcc 7.5, however i have gcc10 installed on the system, i am just trying to figure out how to force make to use gcc10 instead of 7.5

thanks for the help

**Comment by witcherenjoyer** [comment]
here is the make -d output

`GNU Make 4.2.1
Built for x86_64-suse-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Updating makefiles....
 Considering target file 'Makefile'.
  Looking for an implicit rule for 'Makefile'.
  No implicit rule found for 'Makefile'.
  Finished prerequisites of target file 'Makefile'.
 No need to remake target 'Makefile'.
Updating goal targets....
Considering target file 'default_target'.
 File 'default_target' does not exist.
  Considering target file 'all'.
   File 'all' does not exist.
    Considering target file 'cmake_check_build_system'.
     File 'cmake_check_build_system' does not exist.
     Finished prerequisites of target file 'cmake_check_build_system'.
    Must remake target 'cmake_check_build_system'.
Putting child 0x563fde3770f0 (cmake_check_build_system) PID 22570 on the chain.
Live child 0x563fde3770f0 (cmake_check_build_system) PID 22570 
Reaping winning child 0x563fde3770f0 PID 22570 
Removing child 0x563fde3770f0 PID 22570 from chain.
    Successfully remade target file 'cmake_check_build_system'.
   Finished prerequisites of target file 'all'.
  Must remake target 'all'.
Putting child 0x563fde379590 (all) PID 22571 on the chain.
Live child 0x563fde379590 (all) PID 22571 
Reaping winning child 0x563fde379590 PID 22571 
Live child 0x563fde379590 (all) PID 22572 
GNU Make 4.2.1
Built for x86_64-suse-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'CMakeFiles/Makefile2'...
Updating makefiles....
 Considering target file 'CMakeFiles/Makefile2'.
  Looking for an implicit rule for 'CMakeFiles/Makefile2'.
  No implicit rule found for 'CMakeFiles/Makefile2'.
  Finished prerequisites of target file 'CMakeFiles/Makefile2'.
 No need to remake target 'CMakeFiles/Makefile2'.
Updating goal targets....
Considering target file 'all'.
 File 'all' does not exist.
  Considering target file 'external/scope_guard/all'.
   File 'external/scope_guard/all' does not exist.
   Finished prerequisites of target file 'external/scope_guard/all'.
  Must remake target 'external/scope_guard/all'.
  Successfully remade target file 'external/scope_guard/all'.
  Considering target file 'src/all'.
   File 'src/all' does not exist.
    Considering target file 'src/common/all'.
     File 'src/common/all' does not exist.
      Considering target file 'src/common/CMakeFiles/common.dir/all'.
       File 'src/common/CMakeFiles/common.dir/all' does not exist.
       Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/all'.
      Must remake target 'src/common/CMakeFiles/common.dir/all'.
Putting child 0x56463d446560 (src/common/CMakeFiles/common.dir/all) PID 22573 on the chain.
Live child 0x56463d446560 (src/common/CMakeFiles/common.dir/all) PID 22573 
GNU Make 4.2.1
Built for x86_64-suse-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'src/common/CMakeFiles/common.dir/build.make'...
Reading makefile 'src/common/CMakeFiles/common.dir/depend.make' (search path) (no ~ expansion)...
Reading makefile 'src/common/CMakeFiles/common.dir/progress.make' (search path) (no ~ expansion)...
Reading makefile 'src/common/CMakeFiles/common.dir/flags.make' (search path) (no ~ expansion)...
Updating makefiles....
 Considering target file 'src/common/CMakeFiles/common.dir/flags.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/flags.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/flags.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/flags.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/flags.make'.
 Considering target file 'src/common/CMakeFiles/common.dir/progress.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/progress.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/progress.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/progress.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/progress.make'.
 Considering target file 'src/common/CMakeFiles/common.dir/depend.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/depend.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/depend.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/depend.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/depend.make'.
 Considering target file 'src/common/CMakeFiles/common.dir/build.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/build.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/build.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/build.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/build.make'.
Updating goal targets....
Considering target file 'src/common/CMakeFiles/common.dir/depend'.
 File 'src/common/CMakeFiles/common.dir/depend' does not exist.
 Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/depend'.
Must remake target 'src/common/CMakeFiles/common.dir/depend'.
Putting child 0x55bfa3ae7640 (src/common/CMakeFiles/common.dir/depend) PID 22574 on the chain.
Live child 0x55bfa3ae7640 (src/common/CMakeFiles/common.dir/depend) PID 22574 
Reaping winning child 0x55bfa3ae7640 PID 22574 
Removing child 0x55bfa3ae7640 PID 22574 from chain.
Successfully remade target file 'src/common/CMakeFiles/common.dir/depend'.
Reaping winning child 0x56463d446560 PID 22573 
Live child 0x56463d446560 (src/common/CMakeFiles/common.dir/all) PID 22575 
GNU Make 4.2.1
Built for x86_64-suse-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'src/common/CMakeFiles/common.dir/build.make'...
Reading makefile 'src/common/CMakeFiles/common.dir/depend.make' (search path) (no ~ expansion)...
Reading makefile 'src/common/CMakeFiles/common.dir/progress.make' (search path) (no ~ expansion)...
Reading makefile 'src/common/CMakeFiles/common.dir/flags.make' (search path) (no ~ expansion)...
Updating makefiles....
 Considering target file 'src/common/CMakeFiles/common.dir/flags.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/flags.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/flags.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/flags.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/flags.make'.
 Considering target file 'src/common/CMakeFiles/common.dir/progress.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/progress.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/progress.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/progress.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/progress.make'.
 Considering target file 'src/common/CMakeFiles/common.dir/depend.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/depend.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/depend.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/depend.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/depend.make'.
 Considering target file 'src/common/CMakeFiles/common.dir/build.make'.
  Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/build.make'.
  No implicit rule found for 'src/common/CMakeFiles/common.dir/build.make'.
  Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/build.make'.
 No need to remake target 'src/common/CMakeFiles/common.dir/build.make'.
Updating goal targets....
Considering target file 'src/common/CMakeFiles/common.dir/build'.
 File 'src/common/CMakeFiles/common.dir/build' does not exist.
  Considering target file 'src/common/libcommon.a'.
   File 'src/common/libcommon.a' does not exist.
    Considering target file 'src/common/CMakeFiles/common.dir/link.txt'.
     Looking for an implicit rule for 'src/common/CMakeFiles/common.dir/link.txt'.
     No implicit rule found for 'src/common/CMakeFiles/common.dir/link.txt'.
     Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/link.txt'.
    No need to remake target 'src/common/CMakeFiles/common.dir/link.txt'.
    Considering target file 'src/common/CMakeFiles/common.dir/exceptions/path_no_access.cpp.o'.
      Considering target file '../src/common/exceptions/path_no_access.cpp'.
       Looking for an implicit rule for '../src/common/exceptions/path_no_access.cpp'.
       No implicit rule found for '../src/common/exceptions/path_no_access.cpp'.
       Finished prerequisites of target file '../src/common/exceptions/path_no_access.cpp'.
      No need to remake target '../src/common/exceptions/path_no_access.cpp'.
      Pruning file '../src/common/exceptions/path_no_access.cpp'.
      Considering target file '../src/common/exceptions/path_no_access.hpp'.
       Looking for an implicit rule for '../src/common/exceptions/path_no_access.hpp'.
       No implicit rule found for '../src/common/exceptions/path_no_access.hpp'.
       Finished prerequisites of target file '../src/common/exceptions/path_no_access.hpp'.
      No need to remake target '../src/common/exceptions/path_no_access.hpp'.
      Considering target file 'src/common/CMakeFiles/common.dir/flags.make'.
      File 'src/common/CMakeFiles/common.dir/flags.make' was considered already.
     Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/exceptions/path_no_access.cpp.o'.
     Prerequisite '../src/common/exceptions/path_no_access.cpp' is older than target 'src/common/CMakeFiles/common.dir/exceptions/path_no_access.cpp.o'.
     Prerequisite '../src/common/exceptions/path_no_access.cpp' is older than target 'src/common/CMakeFiles/common.dir/exceptions/path_no_access.cpp.o'.
     Prerequisite '../src/common/exceptions/path_no_access.hpp' is older than target 'src/common/CMakeFiles/common.dir/exceptions/path_no_access.cpp.o'.
     Prerequisite 'src/common/CMakeFiles/common.dir/flags.make' is older than target 'src/common/CMakeFiles/common.dir/exceptions/path_no_access.cpp.o'.
    No need to remake target 'src/common/CMakeFiles/common.dir/exceptions/path_no_access.cpp.o'.
    Considering target file 'src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o'.
     File 'src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o' does not exist.
      Considering target file '../src/common/filesystem_utils.cpp'.
       Looking for an implicit rule for '../src/common/filesystem_utils.cpp'.
       No implicit rule found for '../src/common/filesystem_utils.cpp'.
       Finished prerequisites of target file '../src/common/filesystem_utils.cpp'.
      No need to remake target '../src/common/filesystem_utils.cpp'.
      Pruning file '../src/common/filesystem_utils.cpp'.
      Considering target file '../src/common/filesystem_utils.hpp'.
       Looking for an implicit rule for '../src/common/filesystem_utils.hpp'.
       No implicit rule found for '../src/common/filesystem_utils.hpp'.
       Finished prerequisites of target file '../src/common/filesystem_utils.hpp'.
      No need to remake target '../src/common/filesystem_utils.hpp'.
      Considering target file '../src/common/string_utils.hpp'.
       Looking for an implicit rule for '../src/common/string_utils.hpp'.
       No implicit rule found for '../src/common/string_utils.hpp'.
       Finished prerequisites of target file '../src/common/string_utils.hpp'.
      No need to remake target '../src/common/string_utils.hpp'.
      Pruning file 'src/common/CMakeFiles/common.dir/flags.make'.
     Finished prerequisites of target file 'src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o'.
    Must remake target 'src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o'.
Putting child 0x55763d64eb30 (src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o) PID 22576 on the chain.
Live child 0x55763d64eb30 (src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o) PID 22576 
[  2%] Building CXX object src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o
Reaping winning child 0x55763d64eb30 PID 22576 
Live child 0x55763d64eb30 (src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o) PID 22577 
In file included from /home/tom/.steam/arma3unixlauncher/arma3-unix-launcher/src/common/filesystem_utils.cpp:1:0:
/home/tom/.steam/arma3unixlauncher/arma3-unix-launcher/src/common/filesystem_utils.hpp:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Reaping losing child 0x55763d64eb30 PID 22577 
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:93: src/common/CMakeFiles/common.dir/filesystem_utils.cpp.o] Error 1
Removing child 0x55763d64eb30 PID 22577 from chain.
Reaping losing child 0x56463d446560 PID 22575 
make[1]: *** [CMakeFiles/Makefile2:325: src/common/CMakeFiles/common.dir/all] Error 2
Removing child 0x56463d446560 PID 22575 from chain.
Reaping losing child 0x563fde379590 PID 22572 
make: *** [Makefile:147: all] Error 2
Removing child 0x563fde379590 PID 22572 from chain.
`

**Comment by muttleyxd** [comment]
Hi, sorry for my late response but I'm quite busy recently. Since you have GCC10 you should be able to build like this:

```
mkdir build
cd build
cmake .. -DCMAKE_CXX_COMPILER=g++-10
make -j4
```

` -DCMAKE_CXX_COMPILER=g++-10` - this tells CMake to use GCC 10

**Comment by witcherenjoyer** [comment]
Thank you. Worked perfectly for me. Tweaked the launcher just right and im enjoying it now. Good work!
