### ISSUE TITLE
Preprocessor failed with error - Invalid file name (empty file name)

### ISSUE THREAD

**Issue by jurosic** [muttleyxd/arma3-unix-launcher#179]
This error occurs when i start the game from the launcher, i have no idea what it means lol, also the bohemia logos show at the beginning but after that the game is just a black screen. KySysGuard says its eating around 20% cpu and that its sleeping.

**Comment by muttleyxd** [comment]
Hi @jurosic 

please post logs from arma3-unix-launcher, with verbose option, I can't do much without it.

```
arma3-unix-launcher --verbose
```

**Comment by jurosic** [comment]
Yes, sorry my bad.
`[2021-11-29 12:08:12.410] [info] Started Arma 3 Unix Launcher, config file path: "/home/jurosic_park/.config/a3unixlauncher/launcher.conf"
[2021-11-29 12:08:12.413] [debug] arma path: '/home/jurosic_park/.local/share/Steam/steamapps/common/Arma 3', workshop path: '/home/jurosic_park/.local/share/Steam/steamapps/workshop/content/107410'
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Loaded '/home/jurosic_park/.local/share/Steam/linux64/steamclient.so' OK.
[S_API FAIL] SteamAPI_Init() failed; create pipe failed.Icon theme "gnome" not found.
`
this is what happens when i start the launcher.

**Comment by jurosic** [comment]
bump?

**Comment by muttleyxd** [comment]
@jurosic I see that you're running native version of Arma3 (not using Proton), which means it's quite an outdated build, which may not be compatible with mods. Does the game start if you disable all mods? If you click right mouse button mod list, then you'll have an option to disable all mods. If game runs without mods, then it's probably not fault of the launcher.

**Comment by jurosic** [comment]
no, it does not run, i didnt know that the linux version was outdated. Im going to try proton ASAP, thank you for the info!

**Comment by jurosic** [comment]
Okay in very sorry for the incredibly late response, a lot of stuff was happening. But now that i have time i finally installed the proton version of arma3 and now when i try to launch i get this 
`ERROR: ld.so: object '/home/jurosic_park/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/jurosic_park/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: cannot find '/run/media/jurosic_park/New Volume/SteamLibrary/steamapps/common/Arma 3/arma3_x64.exe'
pid 28234 != 28233, skipping destruction (fork without exec?)
`

**Comment by jurosic** [comment]
UPDATE: I managed to get arma working, now the problem im at is that arma hangs when it loads. editor loads but as soon as i press play it starts loading and eventually hangs.

**Comment by muttleyxd** [comment]
If Arma loads correctly, then I can't do much after that. Does it hang without any mods loaded?

**Comment by jurosic** [comment]
ive switched to profiling, and now it loads fine, i forgot to edit my comment, can i close this issue?

**Comment by muttleyxd** [comment]
Good to hear that it works! I can close it myself, sorry for my late responses but I get the time to work on launcher every few weeks.
