### ISSUE TITLE
Request from mailbox: DayZ support

### ISSUE THREAD

**Issue by muttleyxd** [muttleyxd/arma3-unix-launcher#180]
Somebody just asked for adding support for DayZ into arma3-unix-launcher. This could be either done by incorporating DayZ into the launcher or creating a fork of a3ul.

**Comment by BRINGit34** [comment]
Oh yes! please that would be awesome

**Comment by SingerJonathan** [comment]
The CLI launchers currently available for DayZ on Linux haven't been working very consistently for modded servers for me. This launcher for Arma 3 has been working flawlessly so DayZ support would be amazing.

**Comment by muttleyxd** [comment]
Fixed by #195
