### ISSUE TITLE
ENV Variables does not work!

### ISSUE THREAD

**Issue by jarrard** [muttleyxd/arma3-unix-launcher#181]
Just thought I mention the Env variables do not work, for example.

DXVK_FRAME_RATE=70

Does not work. (just as example, not specific)

Are these WINE or LINUX variables that are meant to be here? no descriptions when mousing over these options hurt!

**Comment by muttleyxd** [comment]
![Screenshot with TEST variable working](https://i.imgur.com/8D4N9Iv.png)

seems to work for me (note TEST=1 being added to launch command)

could you post verbose logs from Arma 3 Unix Launcher?

```
arma3-unix-launcher --verbose
```

**Comment by jarrard** [comment]
I'll have another look at it when I have time. I was simply pass MANGOHUD or something via that field and it didn't show in-game but maybe I did something wrong.
