### ISSUE TITLE
"Syntax error: Unclosed bracket" on launch

### ISSUE THREAD

**Issue by 3top1a** [muttleyxd/arma3-unix-launcher#183]
![image](https://user-images.githubusercontent.com/57371001/147612760-e3f7e3ec-5f7e-4f11-bf99-767efbe5fe77.png)

This message appears every time I try to launch Arma from the launcher.
I have tried removing the config multiple times, it has never worked.
The settings also appear not to update, since when launching from steam, it loads up with the contact DLC.
I tried both the version from the Aur and the app image, both produced the same message.

OS: Manjaro Linux x86_64 5.10.84-1-MANJARO
CPU: AMD Ryzen 7 2700 (16) @ 3.400GHz 
GPU: NVIDIA GeForce GTX 1050 Ti

Logs:

```
[2021-12-28 22:53:29.002] [info] Started Arma 3 Unix Launcher, config file path: "/home/not-a-weeb/.config/a3unixlauncher/launcher.conf"
[2021-12-28 22:53:29.002] [debug] arma path: '/qd/Games/steamapps/common/Arma 3', workshop path: '/qd/Games/steamapps/workshop/content/107410'
[S_API] SteamAPI_Init(): Loaded '/home/not-a-weeb/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198302898494 [API loaded no]
[2021-12-28 22:53:29.204] [trace] trying to get workshop mods
[2021-12-28 22:53:32.518] [trace] void MainWindow::on_button_start_clicked():131
[2021-12-28 22:53:32.524] [trace] Mod list: 
```

**Comment by muttleyxd** [comment]
Hey, could you try the newest version. Also please run a3ul with `--verbose` parameter. It'll give us more information what could've gone wrong

`arma3-unix-launcher --verbose`

**Comment by DutchLicorice** [comment]
I was just having a very similar issue to this on my Arch installation so I updated the AUR package and now everything is working fine.

**Comment by 3top1a** [comment]
I guess I didn't close this issue - I recall reinstalling it and doing some basic troubleshooting steps, but then I reinstalled my system, and it worked just fine.
