### ISSUE TITLE
Launcher can't load local mods as active

### ISSUE THREAD

**Issue by scarlett-blake** [muttleyxd/arma3-unix-launcher#185]
Whenever I load a local mod, then exit the launcher and reopen it, the mod is in the list, but unloaded. These mods also have a name "cannot read name".

Console output of the launcher after starting it is such: 
```
[2022-01-04 19:17:01.432] [info] Started Arma 3 Unix Launcher, config file path: "/home/blake/.config/a3unixlauncher/launcher.conf"
[S_API] SteamAPI_Init(): Loaded '/home/blake/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198056681240 [API loaded no]
[2022-01-04 19:17:01.647] [warning] Error loading mod from config:
---
{
  "enabled": true,
  "name": "cannot read name",
  "path": "~arma/@DGRRHSPATCH"
}
--- Reason: filesystem error: directory iterator cannot open directory: No such file or directory [~arma/@DGRRHSPATCH]
```

I have tried:

- .deb release, appimage release
- past versions, the most recent version
- removing the @ from the mod folder name
- moving the mod elsewhere

and the issue persisted across these attempts.

I've also tried changing the mod paths in launcher.conf to absolute, which did help - the launcher loaded the mod correctly - with both the correct loaded state and name. For some reason the launcher can't follow the relative path it sets itself.

A temporary workaround would be setting launcher.conf as read-only, but this, of course, limits all of the launcher's functions other than launching.

**Comment by muttleyxd** [comment]
Fixed by 9f56619. Feel free to reopen if issue persists.
