### ISSUE TITLE
subscribing to mod causes crash

### ISSUE THREAD

**Issue by maocheia** [muttleyxd/arma3-unix-launcher#188]
subscribing to "[Apex RPG7v - v2](https://steamcommunity.com/sharedfiles/filedetails/?id=1814297223&searchtext=Apex+RPG7v)" on the steam workshop causes the arma3-unix-launcher to crash. I'm not sure what is the cause.

```
$ arma3-unix-launcher
[2022-01-14 19:52:18.777] [info] Started Arma 3 Unix Launcher, config file path: "/home/username/.config/a3unixlauncher/launcher.conf"
/usr/include/c++/11.1.0/string_view:234: constexpr const value_type& std::basic_string_view<_CharT, _Traits>::operator[](std::basic_string_view<_CharT, _Traits>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::const_reference = const char&; std::basic_string_view<_CharT, _Traits>::size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
aborted (core dumped)
```

**Comment by muttleyxd** [comment]
Works fine for me, worst type of problem :grin:

Please try verbose option - `arma3-unix-launcher --verbose`

**Comment by maocheia** [comment]
I should have noted that i was using [this aur package](https://aur.archlinux.org/packages/arma3-linux-launcher-git) to install.

`$ arma3-unix-launcher --verbose                                                       ✔  1m 21s  
[2022-02-04 14:29:55.353] [info] Started Arma 3 Unix Launcher, config file path: "/home/username/.config/a3unixlauncher/launcher.conf"
[2022-02-04 14:29:55.354] [debug] arma path: '/run/media/username/HDD/SteamLibrary/steamapps/common/Arma 3', workshop path: '/run/media/username/HDD/SteamLibrary/steamapps/workshop/content/107410'
[2022-02-04 14:29:55.597] [trace] trying to get workshop mods
/usr/include/c++/11.1.0/string_view:234: constexpr const value_type& std::basic_string_view<_CharT, _Traits>::operator[](std::basic_string_view<_CharT, _Traits>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::const_reference = const char&; std::basic_string_view<_CharT, _Traits>::size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
zsh: abort (core dumped)  arma3-unix-launcher --verbose`

now i have noticed that it seems to be missing some dependencies: nlohmann-json pugixml spdlog

so i have tried [this package](https://aur.archlinux.org/packages/arma3-unix-launcher-bin) and got a similar result.
`arma3-unix-launcher --verbose                                                                  ✔ 
[2022-02-04 14:56:13.191] [info] Started Arma 3 Unix Launcher, config file path: "/home/username/.config/a3unixlauncher/launcher.conf"
[2022-02-04 14:56:13.191] [debug] arma path: '/run/media/username/HDD/SteamLibrary/steamapps/common/Arma 3', workshop path: '/run/media/username/HDD/SteamLibrary/steamapps/workshop/content/107410'
[S_API] SteamAPI_Init(): Loaded '/home/username/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198011045889 [API loaded no]
/usr/include/c++/11.1.0/string_view:234: constexpr const value_type& std::basic_string_view<_CharT, _Traits>::operator[](std::basic_string_view<_CharT, _Traits>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::const_reference = const char&; std::basic_string_view<_CharT, _Traits>::size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
zsh: abort (core dumped)  arma3-unix-launcher --verbose`

by using the file in the releases page [arma3-unix-launcher-322.9f56619-1-archlinux-x86_64.pkg.tar.zst](https://github.com/muttleyxd/arma3-unix-launcher/releases/download/commit-322/arma3-unix-launcher-322.9f56619-1-archlinux-x86_64.pkg.tar.zst) i get the same result as the last package

the good news are that by following the build instructions i get no problems!

**Comment by muttleyxd** [comment]
Thank you for the hint with AUR package - for some reason it behaves differently. The reason of this crash were empty values in mod.cpp file, eg. `someValue = ;`. This is now fixed, feel free to reopen if issue persists.
