### ISSUE TITLE
env: ‘steam’: No such file or directory

### ISSUE THREAD

**Issue by 7heLastLoneWolf** [muttleyxd/arma3-unix-launcher#205]
When launching the game via the launcher I receive the error "env: ‘steam’: No such file or directory"
I've installed Steam from Flatpak and used this github page to download the launcher.
This issue is the same as #171. 
#154  Did not solve the problem.

I think I found a solution, had to edit the search paths on steam_utils.hpp so it had a direct path to the steam folder. I'm not too sure if it is a proper or reliable solution, but it fixed the problem on my end.

**Comment by muttleyxd** [comment]
This should be fixed by 164bf27 and #207.

Feel free to reopen if issue persists.
