### ISSUE TITLE
libsteam_api.so not found

### ISSUE THREAD

**Issue by eviscares** [muttleyxd/arma3-unix-launcher#213]
I installed from yay, and it is not starting, erroring out with:
`arma3-unix-launcher: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`
Any suggestion on what is happening here?

**Comment by eviscares** [comment]
The file itself seems to be available
`ls usr/share/arma3-unix-launcher/lib/libsteam_api.so
.rw-r--r-- 336k root 14 Mär 14:14  usr/share/arma3-unix-launcher/lib/libsteam_api.so`

**Comment by muttleyxd** [comment]
This should be fixed by newest release. Feel free to reopen if issue persists.
