### ISSUE TITLE
[linux] cannot detect installation folder. possibility to manually set?

### ISSUE THREAD

**Issue by TheToric** [muttleyxd/arma3-unix-launcher#22]
arma 3's path is 
~/.steam/steam/steamapps/common/Arma 3
and there is no config.vdf that I can find. Is there a way to manually set the path so that I do not have to re-enter it every time?

**Comment by muttleyxd** [comment]
It should be working properly, just when you set it up please close the launcher by 'X' button and then launch it again. It saves settings on exit.

Unfortunately it has a tendency to freeze/crash so if it gets killed, then settings don't get saved

**Comment by muttleyxd** [comment]
Closing this, will be fixed in rewrittren launcher
