### ISSUE TITLE
How to instal/setup

### ISSUE THREAD

**Issue by andersoje2** [muttleyxd/arma3-unix-launcher#23]
I have setup my own linux server. Fully working, but mods dont work no matter what I do. I would like to try this software out. It looks more user friendly. But I cant understand how to get it up and running. Any help would be apreciated.

**Comment by muttleyxd** [comment]
This is for the game, not server. ArmA 3 has been ported to Linux and Mac OS X, but it does not feature a launcher yet.

I have a plan to support launching servers with it, but it's far ahead and I'm not sure when I'll finish it.
