### ISSUE TITLE
Currently incompatible with latest qt5 for Arch packages.

### ISSUE THREAD

**Issue by silikeite** [muttleyxd/arma3-unix-launcher#234]
After updating to the latest qt5 the following error shows up:

`arma3-unix-launcher: symbol lookup error: arma3-unix-launcher: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt2v817basic_string_viewIcEENS_5level10level_enumES6_`

Rolling back the version of qt5 fixes the app but breaks other programs in my system.

**Comment by silikeite** [comment]
Anyways, I tried recompiling the package directly from the git repository and it worked that way with the latest qt5. This seems to purely be an Arch packaging issue.

**Comment by muttleyxd** [comment]
This should be fixed by newest release (commit 370), feel free to reopen if issue persists.
