### ISSUE TITLE
Commit 378 did an Uno-Reverse Card

### ISSUE THREAD

**Issue by Tux0n0** [muttleyxd/arma3-unix-launcher#243]
Since 378 Steam integration is off when starting the launcher using the AppImage and is turned on when the --disable-steam-integration param is given on start.

**Comment by muttleyxd** [comment]
Okay, I kinda got confused by some reports on ArmaOnUnix discord - they told me it's the other way around. On my way to fix it :+1:

**Comment by muttleyxd** [comment]
By the way, I see that you edited the content of original bug report

> Apparently the client can only handle a limited number of mods - freaking out once it's too many.
> It stops downloading from the steam workshop after reaching 99, and is apparently unable to recognize any mods beyond 109.

Is this still an issue?
> Is there any hope of expanding that number?

**Comment by Tux0n0** [comment]
> Is this still an issue?
> 
> > Is there any hope of expanding that number?

Nope it was caused by Steam Integration being disabled normally - which was why when trying to load one of our new packs it didn't download anything at all. As well as some glitchy mods added on top.
