### ISSUE TITLE
Mac OSX launcher not installing

### ISSUE THREAD

**Issue by KingVlad** [muttleyxd/arma3-unix-launcher#25]
-unix-launcher/mac_installer/install-mac.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1194  100  1194    0     0   3518      0 --:--:-- --:--:-- --:--:--  3522
Denises-MBP:~ bensull$ chmod +x ./install-mac.sh
Denises-MBP:~ bensull$ ./install-mac.sh
Checking for git
Checking for Homebrew installation...
Checking for Gtkmm3
Gtkmm3 is installed
Checking for CMake
CMake is installed
Cloning git repository
Cloning into 'arma3-unix-launcher'...
remote: Counting objects: 528, done.
remote: Total 528 (delta 0), reused 0 (delta 0), pack-reused 528
Receiving objects: 100% (528/528), 132.77 KiB | 86.00 KiB/s, done.
Resolving deltas: 100% (324/324), done.
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/FindPkgConfig.cmake:39 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/denisesullivan/a3unixlauncher/arma3-unix-launcher/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
ArmA 3 Unix Launcher built successfully. Moving it into /Applications/
mv: rename arma3-unix-launcher.app to /Applications/arma3-unix-launcher.app: No such file or directory
Denises-MBP:~ bensull$ 

Im a bit of a noob so may need some help fixing this

**Comment by muttleyxd** [comment]
I have updated the script, now it checks if pkg-config is installed and installs it if it's not.

So just please re-download the script and it should work :)

**Comment by KingVlad** [comment]
Cheers

**Comment by muttleyxd** [comment]
If it works please leave a note here, I'll close the issue.
