### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by kl8n2k5** [muttleyxd/arma3-unix-launcher#259]
Using Manjaro KDE, I installed this using the .tar.zst file from the AUR. When I launch from the terminal, I get the following error:
"arma3-unix-launcher: symbol lookup error: arma3-unix-launcher: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt2v917basic_string_viewIcEENS_5level10level_enumES6_"

**Comment by kl8n2k5** [comment]
building from source worked

**Comment by nPHYN1T3** [comment]
Not sure why this is closed, building from source might "fix" it for a user but the appImage is still broken due to this issue. Which comically/sadly defeats the point of something like the appImage format.
