### ISSUE TITLE
Needs to be case insensitive when finding addons

### ISSUE THREAD

**Issue by mr-bo-jangles** [muttleyxd/arma3-unix-launcher#26]

**Comment by muttleyxd** [comment]
Can you post an example where this breaks the launcher or the game?

**Comment by muttleyxd** [comment]
I pushed a new branch, but I cannot test at the moment (no access to any PC which could run ArmA).
I'd like you to test it, in case you don't know how to build it - here are the commands.
```
git clone https://github.com/muttleyxd/arma3-unix-launcher.git fix-case
cd fix-case
git checkout fix-case-sensitivity
mkdir build
cd build
cmake ..
make
./arma3-unix-launcher
```

If it works I'll merge it with master

**Comment by mr-bo-jangles** [comment]
Sorry I've been away. Looks like you have it covered tho and thank you very much!
