### ISSUE TITLE
The launcher simply does not run.

### ISSUE THREAD

**Issue by Akakios1** [muttleyxd/arma3-unix-launcher#264]
I installed the package (commit 383) using the tar.zst and quite frankly it simply does not launch.  It doesn't even throw me an error message.  When I manually went over to the directory it was actually installed to to run it directly through the terminal it spat out this error:
`./arma3-unix-launcher: error while loading shared libraries: libspdlog.so.1.11: cannot open shared object file: No such file or directory
`
Am I missing some sort of dependency or is this just broken?

**Comment by leon4413** [comment]
Same problem on my Arch machine. The author should recompile and reupload the package. In the meanwhile you can build it from source, it's not hard and works pretty well.

I tried things like linking the new library to the old name or downloading the old library, but that leads you to quite the rabbit hole, as spdlog is dependend also on an old version of fmt, but fmt is used by a series of other programs.

**Comment by Akakios1** [comment]
Unfortunately I probably am just going to have to build it from scratch with the source code, still a pain in the ass though.

**Comment by Official-Husko** [comment]
I just experienced this issue as well. Still not fixed?

**Comment by muttleyxd** [comment]
Should be fixed now by, please comment or open a new issue if it still persists

**Comment by Destroyanad** [comment]
Hello i'm having this same issue on 6.12.4-1-MANJARO (64-bit)

**Comment by azeem-io** [comment]
Facing this issue too

**Comment by Destroyanad** [comment]
> Facing this issue too

I've found the app image to work well if you need to use it right now
