### ISSUE TITLE
Issue MAC os 

### ISSUE THREAD

**Issue by nimr77** [muttleyxd/arma3-unix-launcher#268]
CMake Error at src/arma3-unix-launcher/CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by sambarbarin** [comment]
Hi, I've got the exact same issue and didn't found any workaround for this. Does anyone have a clue on how to fix it ?

**Comment by muttleyxd** [comment]
Closing, manual and CI reflect the changes now. Feel free to create a new issue if it still occurs.
