### ISSUE TITLE
Mod load order?

### ISSUE THREAD

**Issue by ragerin** [muttleyxd/arma3-unix-launcher#29]
Is it possible to specify or see the load order of the mods?

**Comment by muttleyxd** [comment]
I don't think so, is there any particular case where it's useful?
I always thought that mod order does not change anything

**Comment by ragerin** [comment]
Mods that correctly specify their dependencies should load in the correct order automatically, but that isn't always the case. Also, some changes to a mod may "ruin" a mod depending on it.

This is why the original launcher allows specifying the load order by dragging the mods around.

I think it would be really awesome to either be able to control mod load order by dragging them around in the unix launcher, too, or at least make the entire launch string the launcher generates, and starts ArmA 3 with internally, visible/selectable.

**Comment by muttleyxd** [comment]
Okay, could you give me names of two example mods which trigger this issue? Would be nice for testing purposes

I think I'd implement this the same way, though I need to think how to deal with with workshop mods being in separate list.

**Comment by muttleyxd** [comment]
I have investigated this issue - you can control mod order, just place the mod you want earlier higher on the list. Workshop mods are now loaded first, then custom mods.
