### ISSUE TITLE
Launcher freezes when game CTD's

### ISSUE THREAD

**Issue by GetzMikalsen** [muttleyxd/arma3-unix-launcher#3]
When I try using some mod that CTDs me then the launcher freezes and the cpu usage goes up to 25% taking one core for itself.
Kinda annoying since it takes alot of tries to get a mod working on linux unless I'm doing something wrong when spawning units in the editor.

**Comment by muttleyxd** [comment]
Thanks for your info. I've heard about the bug, but wasn't able to reproduce it (just heard that launcher sometimes freezes). Going to work on it, will report back in few days.

Also it'd be great if you can tell me what platform are you on and how did you install the launcher?

**Comment by GetzMikalsen** [comment]
OS: Antergos Linux x86_64
  Kernel: 4.9.8-1-ARCH
  Uptime: 2 hours, 36 minutes 
  Packages: 1457 
  Shell: bash 4.4.11 
  Resolution: 2560x1080 
  WM: awesome 
  Theme: Arc-Dark [GTK2/3] 
  Icons: Numix [GTK2/3] 
  Terminal: urxvt 
  CPU: Intel Core i5-3570K (4) @ 3.8GHz 
  GPU: NVIDIA GeForce GTX 970 
  Memory: 5481MB / 7882MB 

I installed it from the AUR.
I tried using the ACE mod with RHS, not doing that again.

**Comment by muttleyxd** [comment]
Fixed by 0627df237c60efdd9791dffc5cadb5dbeffae41f
