### ISSUE TITLE
Proton version

### ISSUE THREAD

**Issue by DrunkenAlcoholic** [muttleyxd/arma3-unix-launcher#31]
Hello muttleyxd,
Love the launcher for the native version for Linux, Just wondering if its possible to create one for the steam proton version as works good on proton. I did download and build and it couldn't find the Arma3.cfg so I changed file path in Filesystem.cpp to "/Games/steamapps/compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/"; and the launcher loaded and showed the current mods I have, It also launched the Arma3 proton version but the mods that I ticked in launcher did'nt load. I believe it might be just a simple modification of the file paths in your launcher. Would it be possible for you too look at it and perhaps make a fork for the proton version?

**Comment by muttleyxd** [comment]
Hi,

That seems doable, I won't have time to work on it for few days, but since you managed to change path in Filesystem.cpp, you could also change one more - line Filesystem.cpp:59
`std::string ArmaConfigFile = LocalSharePrefix + BohemiaInteractivePrefix + "/GameDocuments/Arma 3/Arma3.cfg";`
Please point it to the place where your Arma3.cfg is, I'd check these paths:
```
find /Games/steamapps/compatdata/107410 -iname Arma3.cfg
find ~/Documents -iname Arma3.cfg
```

**Comment by DrunkenAlcoholic** [comment]
awesome thanks mate, just ran it in verbose mode and not sure if this will affect it with this...

`[2019-02-22 21:47:17] /home/drunkenalcoholic/Games/steamapps/compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/
[2019-02-22 21:47:17] Generating Arma3.cfg
[2019-02-22 21:47:17] Reading file /home/drunkenalcoholic/Games/steamapps/compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/... 
[2019-02-22 21:47:17] File read successfully
[2019-02-22 21:47:17] Writing to file /home/drunkenalcoholic/Games/steamapps/compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/
[2019-02-22 21:47:17] Can't open file /home/drunkenalcoholic/Games/steamapps/compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/ for write
[2019-02-22 21:47:17] Arma3.cfg:
`

I'll try your suggestions now and test with modified line 59

**Comment by muttleyxd** [comment]
Something looks weird here, I guess it's time to download Proton version and check out - paths are broken and I don't think you can fix it easily yourself, I'll update when I change something

**Comment by DrunkenAlcoholic** [comment]
here is the verbose output if that help you with anything when you work on it later,
Thanks again mate, appreciated

https://pastebin.com/yGY5aXNv

**Comment by ninelore** [comment]
FYI: This is why the Launcher isnt working: https://github.com/ValveSoftware/Proton/issues/18

**Comment by DrunkenAlcoholic** [comment]
Any updates muttley?

**Comment by muttleyxd** [comment]
I added Proton support to arma3-unix-launcher: https://github.com/muttleyxd/arma3-unix-launcher/pull/32

```
git clone https://github.com/muttleyxd/arma3-unix-launcher.git
cd arma3-unix-launcher
git checkout add-proton
mkdir build && cd build
cmake ..
make -j4
./arma3-unix-launcher
```

Please tell me if it works, if yes, then I'll merge with master

**Comment by muttleyxd** [comment]
Added Proton support to master https://github.com/muttleyxd/arma3-unix-launcher/commit/cf28a5860ba5633540cc676aa56b82f74e4d63da , also available in AUR, please check if it works correctly.

**Comment by muttleyxd** [comment]
Correct implementation in e4f157e1942d0c437d81512849d754fc41cdd972

**Comment by DrunkenAlcoholic** [comment]
Work great for me, good job, hopefully future versions of proton will have
battleye working

Thank you muttlyxd
