### ISSUE TITLE
Proton: add option to run with 'esync' disabled

### ISSUE THREAD

**Issue by muttleyxd** [muttleyxd/arma3-unix-launcher#33]
As described

**Comment by muttleyxd** [comment]
After rethinking: it's irrelevant, should be controlled by Steam (`PROTON_NO_ESYNC=1 %command%`), since it's too dependent on user's configuration.

**Comment by ShaunTheQuietGamer** [comment]
It isn't controlled by steam when launched through the launcher though, and if its supposed too, it isn't.
