### ISSUE TITLE
Proton launcher looks in $HOME/.steam instead of the library.

### ISSUE THREAD

**Issue by beef331** [muttleyxd/arma3-unix-launcher#34]
Instead of looking at the steam library Arma3 is installed at for compdata it looks at home. My Arma is installed at /media/jason/HDD/SteamLibrary but instead it's looking for the .cfg at /home/jason/.steam

**Comment by muttleyxd** [comment]
I'm taking Steam's path for compatdata/ instead of game's path. Will be fixed tommorrow

**Comment by muttleyxd** [comment]
Fixed in e4f157e1942d0c437d81512849d754fc41cdd972
