### ISSUE TITLE
Arma starts without Mods, even with Mods selected in the unix launcher

### ISSUE THREAD

**Issue by ninelore** [muttleyxd/arma3-unix-launcher#35]
there are no mods in the parameter string (checked with htop), nor in the Arma3.cfg
Pls tell me if u need more info

**Comment by muttleyxd** [comment]
Three things:

1. This is probably caused by recently Proton compatibility addition.
2. Are you using Native or Proton version?
3. Please give me following information:
- output of 'arma3-unix-launcher --verbose'
- location of Arma 3 install
- location of Arma 3 cfg file

**Comment by ninelore** [comment]
i was shure i forgot something lol

Im using Proton Version (4.2-2)

Arma3: ~/.local/share/Steam/steamapps/common/Arma 3

Arma3.cfg ~/.local/share/Steam/steamapps/compatdata/107410/pfx/drive_c/Users/steamuser/Documents/Arma 3/arma3.cfg

ill post --verbose output in a few minutes

**Comment by ninelore** [comment]
https://gist.github.com/ninelore/693e70852897ed61d98970787ce04987

**Comment by muttleyxd** [comment]
I have a question about this path:
`~/.local/share/Steam/steamapps/compatdata/107410/pfx/drive_c/Users`

Note that it's "Users" and not "users"
Can you confirm that this directory starts with 'U' letter?

Also I see some directory errors related to paths, did you try doing
`arma3-unix-launcher --purge`
Note that it will delete all files created by launcher, config files too.

If purge won't help, I'll try to reproduce these on weekend.

**Comment by ninelore** [comment]
should be the standard path of wine prefix documents folder. i just guessed it cus i was not at pc, but its the true one exept of maybe Capital Letters.

When I read the verbose output, I read something about failed to create symlinks. Should I try sudo the launcher eventually?

**Comment by ninelore** [comment]
I think the problem is on my side. Closing
