### ISSUE TITLE
Startup crash with segfault from steam update (steamwebhelper cmdline starts with null character)

### ISSUE THREAD

**Issue by VurtualRuler98** [muttleyxd/arma3-unix-launcher#36]
I first experienced the launcher crashing on launch from a segfault after a steam beta update, after rolling back to the stable client the crash stopped. After the beta update became stable, the crash returned. Doing some investigating with gdb, the segfault is in Utils.cpp on line 163, called from MainWindow.cpp line 319. The process it's looking at before crashing is a steamwebhelper zygote process, whose cmdline begins as " /steamwebhelper" (note leading space, in /proc/PID/cmdline it's a null character) and not "./steamwebhelper" like the others. The value "first" then becomes 0x0 instead of the process name when tokenized, which makes strcmp fail, I guess. Closing steam fixes the issue, as does killing the steamwebhelper processes, but neither is a good fix.

#28 might be related.

**Comment by muttleyxd** [comment]
Please rebuild with master and check if issue still persists - I rewrote FindProcess implementation.

**Comment by VurtualRuler98** [comment]
Built the newest version from master and it works fine now, no crash while the offending steamwebhelper is running.
