### ISSUE TITLE
Arma3.cfg not found

### ISSUE THREAD

**Issue by Gloomshroud** [muttleyxd/arma3-unix-launcher#37]
Hello, running Xubuntu 18.10. I am able to launch Arma3, using Proto 4.2-3 (forced). 

However, this is the output of .**/arma3-unix-launcher --verbose** (both as root and not). I think the issue may be related to Proton (the launcher doesn't seem to be detecting that I'm using Proton).

I checked your code, and it seems to look in the compatdata folder for the Arma3.cfg file (which is there and does exist). However, I can't seem to find a branching statement that determines if and where Proton exists.
```
[2019-04-22 21:46:46] ArmA 3 Unix Launcher started
[2019-04-22 21:46:46] Reading file /home/gloomshroud/.config/a3unixlauncher/settings.conf... 
[2019-04-22 21:46:46] File read successfully
(arma3-unix-launcher:9748): IBUS-WARNING **: 21:46:46.572: The owner of /home/gloomshroud/.config/ibus/bus is not root!
GTK+ version: 3.24.4
Glib version: 2.58.1
[2019-04-22 21:46:46] IS NOT PROTON
[2019-04-22 21:46:46] ArmA 3 Path: /home/gloomshroud/.steam/steam/steamapps/common/Arma 3
Workshop mods path: /home/gloomshroud/.steam/steam/steamapps/workshop/content/107410
[2019-04-22 21:46:46] Creating Arma3.cfg backup...
[2019-04-22 21:46:46] Arma3.cfg does not exist
Please run Arma at least once before using launcher

```

**Comment by muttleyxd** [comment]
Hello, could you send me output of:
`ls -a /home/gloomshroud/.steam/steam/steamapps/common/Arma 3`

Launcher is looking for arma3_x64.exe and it doesn't seem to be detected, it may not be there or something is wrong wtih the code.

**Comment by Gloomshroud** [comment]
Ahhh, well then that may be the problem. I renamed it to arma3launcher! I'll check that and see if it fixes the problem. Edit incoming.
