### ISSUE TITLE
Program received signal SIGABRT

### ISSUE THREAD

**Issue by salamanderrake** [muttleyxd/arma3-unix-launcher#4]
KDE Neon (Ubuntu 16.04 based)
GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

> gdb ./arma3-unix-launcher 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Warning: /home/rake/bin/opt/VulkanSDK/1.0.21.1/source/layers: No such file or directory.
Warning: /home/rake/bin/opt/VulkanSDK/1.0.21.1/source/loader: No such file or directory.
Warning: /home/rake/bin/opt/VulkanSDK/1.0.21.1/examples: No such file or directory.
Warning: /mnt/store/UnrealEngine/Unrealcourse/04_BattleTank/BattleTank/Source: No such file or directory.
Warning: /mnt/store/UnrealEngine/Unrealcourse/04_BattleTank/BattleTank/Source/BattleTank: No such file or directory.
Reading symbols from ./arma3-unix-launcher...done.
(gdb) r
Starting program: /home/rake/src/arma3-unix-launcher/build/arma3-unix-launcher 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2017-03-31 17:18:31] ArmA 3 Unix Launcher started
terminate called after throwing an instance of 'Gtk::BuilderError'
Program received signal SIGABRT, Aborted.
0x00007ffff5851428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

> (gdb) bt full
#0  0x00007ffff5851428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 12857
        selftid = 12857
#1  0x00007ffff585302a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7ffff5be0540 <_IO_2_1_stderr_>, sa_sigaction = 0x7ffff5be0540 <_IO_2_1_stderr_>}, 
          sa_mask = {__val = {140737312803839, 140737316259136, 2, 2, 140737348282448, 140737316259584, 8280688, 140737353189920, 
              8280544, 1, 140737353192272, 8280544, 140737319053290, 140737488342592, 140737488346032, 140737348282448}}, 
          sa_flags = -169314176, sa_restorer = 0x7ffff7a6a850 <typeinfo name for Gtk::BuilderError>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff5e8a84d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff5e886b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff5e88701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff5e88919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7985e87 in Gtk::BuilderError::throw_func(_GError*) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
No symbol table info available.
#7  0x00007ffff7231d12 in Glib::Error::throw_exception(_GError*) () from /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
No symbol table info available.
#8  0x00007ffff79864db in Gtk::Builder::add_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
No symbol table info available.
#9  0x00007ffff7986510 in Gtk::Builder::create_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
No symbol table info available.
#10 0x00000000004707e1 in main (argc=0, argv=0x7fffffffdbb8) at /home/rake/src/arma3-unix-launcher/main.cpp:120
        app = {pCppObject_ = 0x7402d0}
        MainFormPath = "/home/rake/src/arma3-unix-launcher/MainForm.glade"
        builder = {pCppObject_ = 0x7ffff7fbe9f0}
        mainWindow = 0x7ffff7fbe9f0
(gdb)

**Comment by muttleyxd** [comment]
Hey, if I'm reading this correctly: launcher cannot find MainForm.glade file. Try copying it into directory where binary is located. If it is the fix, then I'll fix it in CMakeLists.txt

**Comment by salamanderrake** [comment]
I did that, same error.

**Comment by muttleyxd** [comment]
Honestly, I have no idea what could cause this.

Did you try .deb package that's available on Releases tab?

I'll probably set up myself a VM with Neon and try to do something from there, but that's for tomorrow, out of house for weekend  :(

**Comment by salamanderrake** [comment]
It may be that my libgtkmm is not new enough,
> sudo dpkg -i /home/rake/Downloads/arma3-unix-launcher_32-e2fe2c8-ubuntu_amd64.deb 
Selecting previously unselected package arma3-unix-launcher.
(Reading database ... 339120 files and directories currently installed.)
Preparing to unpack .../arma3-unix-launcher_32-e2fe2c8-ubuntu_amd64.deb ...
Unpacking arma3-unix-launcher (32-e2fe2c8-ubuntu) ...
dpkg: dependency problems prevent configuration of arma3-unix-launcher:
 arma3-unix-launcher depends on libgtkmm-3.0-1v5 (>= 3.18.1-1); however:
  Version of libgtkmm-3.0-1v5:amd64 on system is 3.18.0-1.

dpkg: error processing package arma3-unix-launcher (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 arma3-unix-launcher

**Comment by muttleyxd** [comment]
Damn, KDE Neon's packages are old :P

**Comment by salamanderrake** [comment]
Its based on Ubuntu 16.04, so yeah, its old.

**Comment by muttleyxd** [comment]
Fixed, related to #5 , closing.
