### ISSUE TITLE
Symlinking fails if a mod has a / in its name.

### ISSUE THREAD

**Issue by Baguettedood** [muttleyxd/arma3-unix-launcher#41]
When subscribing to [ZEC - Zeus and Eden Templates / Building Compositions](https://steamcommunity.com/sharedfiles/filedetails/?id=642912021) and opening the Arma3 Unix Launcher, the terminal output throws an error when attempting to symlink this mod:

`Symlink creation failed: /home/<my username>/.steam/steam/steamapps/workshop/content/107410/642912021->/home/<my username>/.steam/steam/steamapps/common/Arma 3/!workshop/@ZEC - Zeus and Eden Templates / Building Compositions`

Although the mod.cpp file (and the launcher's GUI itself) calls the mod "[ZEC] Compositions", the meta.cpp has a larger name with the slash included, which fails the symlink probably because Linux is interpreting the / as a folder.

Launching Arma after selecting this mod just shows blank information since it never actually loaded the mod.

**Comment by muttleyxd** [comment]
Nice find, fixed now.
