### ISSUE TITLE
Custom mods are never loaded

### ISSUE THREAD

**Issue by x-00010** [muttleyxd/arma3-unix-launcher#42]
No matter what I do, mods selected from their folders which I have downloaded are never loaded by the app. 
They're not written into the Arma3.cfg file, but workshop ones are.

This makes the custom mod selection unusable.

**Comment by x-00010** [comment]
Note: I'm also getting an error when I run the program through the terminal which states several times
>Not a symlink found in ModDirs!

**Comment by forest-hermit** [comment]
I think is related to this one #40

**Comment by forest-hermit** [comment]
It works perfectly with the latest build! Thanks for your help @muttleyxd !

**Comment by muttleyxd** [comment]
@x-00010 
Can you check if it got fixed by newest master?

**Comment by x-00010** [comment]
Yeah, will give it a go.

**Comment by muttleyxd** [comment]
@x-00010 any update on this?

**Comment by muttleyxd** [comment]
Closed as stale, feel free to reopen if issue persists.
