### ISSUE TITLE
no quit button

### ISSUE THREAD

**Issue by slavachertanovo** [muttleyxd/arma3-unix-launcher#49]
there is a little problem, preventing use of this launcher in tiling window managers without window decoration - the lack of the quit button. I can only kill it with xkill or command line.

**Comment by muttleyxd** [comment]
Fixed with 6bbeb7d17f9d1b6305f11747041d74814e642842

I've added 'Other' tab, which contains 'Quit' button.

Feel free to reopen the issue if the issue persists

**Comment by muttleyxd** [comment]
I forgot to reimplement this in rewritten launcher, have to redo this
