### ISSUE TITLE
Incorrect steam install location

### ISSUE THREAD

**Issue by salamanderrake** [muttleyxd/arma3-unix-launcher#5]
Steam no longer installs into ~/.local/share but ~/.steam,
I applied this patch and I believe it found the install of steam, still don't know if it works as there are still issues with the application its self.

Patch:
https://gist.github.com/salamanderrake/aa4e0711b7c3a2460d836baef6bcd7a6

**Comment by muttleyxd** [comment]
IIRC "~/.steam" is a symlink to "~/.local/share/steam/steam"

At least it was on Manjaro, will have to verify with other distros.

**Comment by salamanderrake** [comment]
>ls -lha ~
drwxrwxr-x    25 rake rake 4.0K Mar 31 17:54 .steam
lrwxrwxrwx     1 rake rake   29 Mar 31 17:54 .steampath -> /home/rake/.steam/bin32/steam
lrwxrwxrwx     1 rake rake   27 Mar 31 17:54 .steampid -> /home/rake/.steam/steam.pid

**Comment by muttleyxd** [comment]
Okay, so when I get back home I'll check it out and create some kind of workaround - I'm 90% sure that Arch-based distros have it the old way, so some kind of detection will be needed

**Comment by muttleyxd** [comment]
Ubuntu-based distros are really surprising. I've installed libgtkmm-3.0-1v5 to build the launcher. Totally didn't expect that installing developer's package would not insatll gtkmm-3.0.

However I'm preparing a simple patch for this, when it's ready I'll create a new branch for you to check and see if it's fixed.

**Comment by muttleyxd** [comment]
I have created a branch with fixes - it starts now for me on KDE Neon.
Please verify if problem is fixed.

```
git clone https://github.com/muttleyxd/arma3-unix-launcher.git
cd arma3-unix-launcher
git checkout fix-kde-neon
mkdir build
cd build
cmake ..
make
```

**Comment by salamanderrake** [comment]
Works, thanks

**Comment by muttleyxd** [comment]
Okay, merging it with master then.
