### ISSUE TITLE
Readme addition (cmake)

### ISSUE THREAD

**Issue by TriMoon** [muttleyxd/arma3-unix-launcher#51]
Seems you forgot to mention that you also need to install `cmake` at [README.md#debian-package](https://github.com/muttleyxd/arma3-unix-launcher/blob/master/README.md#debian-package)
Otherwise you can't do the step `cmake ..` :wink: 
After that it seems to succeed without errors on my Kubuntu 19.10 so far :+1:

**Comment by muttleyxd** [comment]
Fixed with 29601f6b19f3f754ea3827fdebaf3eba9153fecc

Feel free to reopen the issue if the issue persists :)
