### ISSUE TITLE
command-line for autostart with config to use?

### ISSUE THREAD

**Issue by TriMoon** [muttleyxd/arma3-unix-launcher#52]
Is there a command-line to autostart arma3 using an arma3-unix-launcher config file of choice?
This would be very handy to create desktop files with menu entries etc...
Ofcourse this would imply auto-exit of the unix launcher upon exit of the game :wink:

**Comment by muttleyxd** [comment]
> Is there a command-line to autostart arma3 using an arma3-unix-launcher config file of choice?
For now there isn't an option

I guess I could add two options:
- ```--config-file``` to specify where config file is located (has all mods/options loaded)
- ```--run-arma``` to run Arma after starting and exit

What do you think about that?

**Comment by TriMoon** [comment]
I meant to use a command line option to specify a preset you can choose in the GUI to auto start with.

You know in the GUI you can click load to load a preset you have saved, then click play?
After you exit the game arma3-unix-launcher resets the config used to what was there before it right?

So i would suggest to use somekind of `--preset` option. (Maybe a `--play-preset`?)
When that option is present it will skip the GUI to automate the loading of that preset, starting the game and after exit of game reset the config back to previous state and exit the launcher.
All this without a GUI that stays in screen and memory...
For this reset of config you would still need to make the launcher wait for the game to exit? :wink:

**Comment by muttleyxd** [comment]
I think resetting config is kinda pointless, I've got rid of it with 1d47586e2117419b070302a1428ba19b8a0b7f6e.

> You know in the GUI you can click load to load a preset you have saved, then click play?

Actually I forgot about it :D

Anyway, I'm implementing it now.

**Comment by muttleyxd** [comment]
Early implementation is available on `add-preset-to-run` branch, could you check if it works correctly?

```
git clone https://github.com/muttleyxd/arma3-unix-launcher.git
cd arma3-unix-launcher
git checkout add-preset-to-run
mkdir build
cd build
cmake ..
make
./arma3-unix-launcher --preset-to-run <some_name>
```

`<some_name>` can be a relative path, absolute path or filename in `~/.config/a3unixlauncher`

So if you have a file `~/.config/a3unixlauncher/somemods.a3ulm` you can start the launcher with
```
./arma3-unix-launcher --preset-to-run somemods
```

**Comment by TriMoon** [comment]
> Early implementation is available on `add-preset-to-run` branch, could you check if it works correctly?
Not at moment because im trying to setup [this repo](https://gitlab.com/trimoon-inc/Arma3_DS) to automate setting up a DS. (Currently force pushing initial commits with changes)
When i'm done with a working initial commit of that i will try :wink:

**Comment by TriMoon** [comment]
I already had the repo so i needed to do:
```console
cd <arma3-unix-launcher>
git fetch
git checkout add-preset-to-run
cd build
cmake ..
make
./arma3-unix-launcher --preset-to-run <some_name>
```
Where `<some_name>` is located inside `~/.config/a3unixlauncher`.
- I used both `noMods` and `noMods.a3ulm` for the `<some_name>` as that is the name of the preset i created.
This is output after arma3-unix-launcher was for both:
```console
[2020-01-18 09:24:10] ArmA 3 Unix Launcher started
GTK+ version: 3.24.12
Glib version: 2.62.1
[2020-01-18 09:24:10] Config path: /SteamGameLib/mainuser/steamapps/common/Arma 3/../../compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/Arma3.cfg
[2020-01-18 09:24:10] ArmA 3 Path: /SteamGameLib/mainuser/steamapps/common/Arma 3
Workshop mods path: /SteamGameLib/mainuser/steamapps/workshop/content/107410
[2020-01-18 09:24:10] Not a symlink found in ModDirs!
[2020-01-18 09:24:10] Not a symlink found in ModDirs!
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@RHS: United States Forces already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@$STR_A3_cfgmods_oldman_name0 already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@FIR Pilot&Crew Pack already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@F-16 Fighting Falcon already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@Devas Turkish Armed Forces Mod already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@TMT - Turkish Forces v0.7 already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@FIR AWS(AirWeaponSystem) already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@TMT - TuAF F-16C already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@Community Base Addons v3.13.0 already exists
[2020-01-18 09:24:10] Dir/file /SteamGameLib/mainuser/steamapps/common/Arma 3/!workshop/@LBT 6094 already exists
[2020-01-18 09:24:10] Status monitoring thread started
[2020-01-18 09:24:11] FullModList size:10
[2020-01-18 09:24:11] /SteamGameLib/mainuser/steamapps/common/Arma 3/../../compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/Arma3.cfg
[2020-01-18 09:24:11] Generating Arma3.cfg
```
The command returned the prompt but arma3 was not started...
Without the argument it opened the GUI as usual, but didn't start Arma3 when play was clicked...
Then i checked-out the `master` branch and repeated the make steps and ran `arma3-unix-launcher` to see if it would open arma3, but it didn't either.
So i need to check and see which arma3 version i have installed at moment, will comeback to this soon...

**Comment by TriMoon** [comment]
Update unfortunately the `add-preset-to-run` does not launch the game at all, with or without the  `--preset-to-run` parameter.
It does however create the config file in both cases.
But because the client version of the linux version is still behind (1.82) i am switching back to the proton version after a complete uninstall of arma3...

**Comment by muttleyxd** [comment]
@TriMoon 
I didn't test native version, so I guess I should do that now. Worked fine for me with Proton

**Comment by TriMoon** [comment]
@muttleyxd please see #55

**Comment by muttleyxd** [comment]
Please check now, I've updated this branch, you'll to do a hard reset
```
git fetch origin
git checkout add-preset-to-run
git reset --hard origin/add-preset-to-run
#rest of build commands
```

**Comment by TriMoon** [comment]
Thanks i have just checked the master branch with your fix and it successfully started arma.
I will try this branch tomorrow :wink:

**Comment by TriMoon** [comment]
@muttleyxd 
I installed `arma3-unix-launcher_add-preset-to-run-98-5176787-ubuntu-x86_64.deb`, and seems this branch is working fine now.

Just a suggestion to you for the `.deb`:
- Can you add an icon to the desktop file?\
It looks a bit weird with a blank icon :smile: 
  - I used [this logo](https://gitlab.com/trimoon-inc/Arma3_DS/blob/master/images/arma3_logo.png) using:\
`sudo install --mode=0644 images/arma3_logo.png /usr/share/icons/hicolor/512x512/apps/a3unixlauncher.png`
And adding `Icon=a3unixlauncher` to the desktop file and it looks much nicer now :wink: \
Feel free to use the one i used which is not mine but found on the internet or any other image...

**Comment by TriMoon** [comment]
@muttleyxd is there also a way to specify command-line paramters to arma3?
Because those settings are not saved inside the presets but as global settings of this launcher.

I would like to use [these options](https://community.bistudio.com/wiki/Arma_3_Startup_Parameters) on the command-line from the desktop file:
- `-name=<string>` 	Profile name. 
- `-connect=<ip>` 	Server IP to connect to.
- `-port=<number>` 	Server port to connect to.
- `-password=<string>` 	Server password to connect to. 

I know we can set those inside this launcher, but it would be much handier if we could override those on the command line, to ease desktop entries to use different settings :wink:

**Comment by muttleyxd** [comment]
I think both of these should be separate issues :grin:

Currently there isn't a way to specify command-line parameters but I'll definitely add a parameter, good idea

Closing this one, feel free to reopen if there's something more
