### ISSUE TITLE
How to use the launcher on external hard drive?

### ISSUE THREAD

**Issue by NightHunter3007** [muttleyxd/arma3-unix-launcher#54]
I installed Arma 3 on a WD element external hard drive because the space in my macbook was not enough , and I have already installed the arma 3 unix launcher successfully. But the launcher does not access to the hard drive, so I can not save any mod file to the arma 3 game file inside the hard drive.

Is there any way, method or code that can enable me to access the launcher to the hard drive?

**Comment by TriMoon** [comment]
Then you should probably modify `~/.config/a3unixlauncher/settings.conf` and change the value of `ArmaPath`.

**Comment by NightHunter3007** [comment]
But how to change the armapath ?

**Comment by TriMoon** [comment]
The file i mentioned above is a configuration file, so you need to edit it and change the value of `ArmaPath` inside it to reflect the location of your arma3 install....
Because no one besides you kn ow the exact location of your install, no one will be able to give you a definitive value to put there...

**Comment by NightHunter3007** [comment]
But my latop is a macbook pro 2018, not a linux

**Comment by TriMoon** [comment]
You didnt tell me that, but np because it still has an operating system based on Unix :wink:
So use any text editor on your Macbook...

**Comment by muttleyxd** [comment]
@NightHunter3007 
What Mac version do you have exactly?

Config file should be stored at
`~/Library/Application Support/.config/a3unixlauncher/settings.conf`

If it isn't there, just create it with following content
```
ArmaPath=/path/where/your/arma/is
WorkshopPath=/path/to/steam/workshop/files
```

usually it should be something like

```
ArmaPath=/your/disk/SteamLibrary/common/Arma 3
WorkshopPath=/your/disk/SteamLibrary/workshop/107410
```

@TriMoon 
Unfortunately there are some differences between Linux and Mac, some paths don't exist.

**Comment by NightHunter3007** [comment]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
And I change use optic+command+c to find the path of my arma 3 file
![螢幕截圖 2020-01-23 上午10 55 37](https://user-images.githubusercontent.com/58033268/72953132-15b61300-3dcf-11ea-9c11-2bfdee310bce.png)

**Comment by NightHunter3007** [comment]
Mac Mojave 10.14.6

**Comment by muttleyxd** [comment]
@NightHunter3007 
Well, I didn't mean that, to make it easier for you you can run this command and it will create the file (just paste it into terminal and click enter)

```bash
mkdir -p ~/Library/Application Support/.config/a3unixlauncher
echo "ArmaPath=/Volumes/Hard Disk/Steam games/steamapps/common/Arma 3
WorkshopPath=/Volumes/Hard Disk/Steam games/steamapps/workshop/content/107410" > ~/Library/Application Support/.config/a3unixlauncher/settings.conf
```

**Comment by NightHunter3007** [comment]
Thank you for your help and instructions, I can finally install it on my MacBook.
And I have one last question, how to use the launcher?

<img width="868" alt="螢幕截圖 2020-01-24 下午3 37 33" src="https://user-images.githubusercontent.com/58033268/73118500-e8649300-3f8f-11ea-949a-a8585d494c40.png">

<img width="455" alt="螢幕截圖 2020-01-25 下午4 35 15" src="https://user-images.githubusercontent.com/58033268/73118637-c79d3d00-3f91-11ea-9581-687ae0a62ea1.png">


Should I put the mods in this location? 
/Volumes/Hard Disk/Steam games/steamapps/workshop/content/107410

**Comment by NightHunter3007** [comment]
<img width="912" alt="螢幕截圖 2020-01-25 下午4 49 30" src="https://user-images.githubusercontent.com/58033268/73118711-b0ab1a80-3f92-11ea-8bfe-49fe87c7c223.png">
I clicked all of the boxes and pressed the (p) button to run the game, but nothing changed, I still can not play the custom campaigns and use the mods

**Comment by NightHunter3007** [comment]
And I noticed that after I clicked all of the boxes, my steam account has not started downloading anything from the internet.

**Comment by muttleyxd** [comment]
You can put your mods in Arma's main directory, that is `/Volumes/Hard Disk/Steam games/steamapps/common/Arma 3`

So it can be like
```
/Volumes/Hard Disk/Steam games/steamapps/common/Arma 3/@mod1
/Volumes/Hard Disk/Steam games/steamapps/common/Arma 3/@mod2
/Volumes/Hard Disk/Steam games/steamapps/common/Arma 3/@mod3
```

> And I noticed that after I clicked all of the boxes, my steam account has not started downloading anything from the internet.

Steam should download all the mods, if it doesn't then it's a problem with Steam and I can't do much about it :(


> ![](https://user-images.githubusercontent.com/58033268/73118637-c79d3d00-3f91-11ea-9581-687ae0a62ea1.png)

Were you trying to add a new mod? A mod should have 'addons' directory inside it (with .pbo files inside 'addons' directory)

**Comment by NightHunter3007** [comment]
/Volumes/Hard Disk/Steam games/steamapps/common/Arma 3/@mod1/1291405135

?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/02/20
上午12:19:30

Mateusz Szychowski (Muttley) <notifications@github.com> 於 2020年2月3日 週一
上午1:41寫道：

**Comment by muttleyxd** [comment]
Closing as stale. Feel free to reopen if issue persists.
