### ISSUE TITLE
How to use the launcher?

### ISSUE THREAD

**Issue by NightHunter3007** [muttleyxd/arma3-unix-launcher#58]
Video:
https://drive.google.com/file/d/1voVYxl8gfjNZYNoTueDZ1i5feiPapuqa/view?usp=sharing

I clicked all of the boxes, and press the button to run Arma 3, but no new mod ,campaign and weapon were added to the game

<img width="1280" alt="螢幕截圖 2020-02-24 下午4 09 17" src="https://user-images.githubusercontent.com/58033268/75137470-a495b280-5722-11ea-8b87-196eacc8a413.png">
<img width="1280" alt="螢幕截圖 2020-02-24 下午4 09 02" src="https://user-images.githubusercontent.com/58033268/75137509-bd05cd00-5722-11ea-896a-130299090244.png">

**Comment by muttleyxd** [comment]
There is a bug with custom profiles #57 
Please disable Profile option (Parameters -> Profile)

![params](https://user-images.githubusercontent.com/9843181/75331309-c1e19280-5882-11ea-898a-ab9fadabaa05.png)

**Comment by muttleyxd** [comment]
@NightHunter3007 
Can you check if it got fixed by newest master?

**Comment by NightHunter3007** [comment]
What do you mean about the ‘newest master’ ? Do I have to redownload the
launcher? I have not noticed any change

「Mateusz Szychowski (Muttley) <notifications@github.com>」在 2020年3月4日
週三，下午9:44 寫道：

**Comment by muttleyxd** [comment]
Closing as stale. Feel free to reopen if issue persists.
