### ISSUE TITLE
Mod without @, can't find them

### ISSUE THREAD

**Issue by Crafol** [muttleyxd/arma3-unix-launcher#74]
The launcher works without problem when detecting Arma 3 and when executing it without mod. But it can't find the mods that I download from WORKSHOP.
![Captura de pantalla de 2020-04-03 18-20-25](https://user-images.githubusercontent.com/3323764/78405959-fcec8980-75d7-11ea-81c4-80ee936db92d.png)
![Captura de pantalla de 2020-04-03 18-16-25](https://user-images.githubusercontent.com/3323764/78405973-0249d400-75d8-11ea-8f2e-7c4a75c8ecc0.png)

**Comment by muttleyxd** [comment]
Can you please post output of this command?

```shell
cat ~/.config/a3unixlauncher/launcher.conf
```

It looks like something's wrong with paths, so that's where I'd start

**Comment by Crafol** [comment]
Yes of course. : D

```
{
    "mods": {
        "custom": [],
        "workshop": []
    },
    "parameters": {
        "checkSignatures": false,
        "connect": null,
        "cpuCount": 4,
        "customParameters": null,
        "enableHT": false,
        "exThreads": -1,
        "filePatching": false,
        "host": false,
        "hugepages": false,
        "name": null,
        "noLogs": false,
        "noPause": false,
        "noSplash": true,
        "par": null,
        "password": null,
        "port": null,
        "skipIntro": true,
        "window": false,
        "world": null
    },
    "paths": {
        "arma": "/home/crafol/.local/share/Steam/steamapps/common/Arma 3",
        "workshop": "/home/crafol/.local/share/Steam/steamapps/workshop"
    }
}
```
I tried to check the PATHs, but I couldn't figure out what was wrong. I changed them to the places that I thought should work, but did nothing.

As important data. Install Steam with FlatPak first but when it didn't work it went back to the repositories version.

I am using Reborn OS, derived from Archlinux.

Thank you.
(If not understood it is the fault of the Google translator :))

**Comment by Crafol** [comment]
Sorry, I accidentally closed it.

**Comment by muttleyxd** [comment]
Try changing workshop's path to

```
"workshop": "/home/crafol/.local/share/Steam/steamapps/workshop/content/107410"
```

Did the launcher detect Arma automatically or did you have to select installation directory first time when you used it?



> (If not understood it is the fault of the Google translator :))

It's fine, I can understand you very well :)

**Comment by Crafol** [comment]
The Launcher detected it automatically.
I made the change, but it still doesn't work.

I also dealt with ASMA, the competition, but in order for it to take the mod I had to create symbolic links of the directories in the route of Arma 3, and that is what makes it more tedious, almost useless because I only see the mod IDs. I don't know if it contributes something, but it helps out there.

**Comment by muttleyxd** [comment]
Okay, from what I see, only mods which you have subscribed are mission mods - they don't appear in launcher since you don't need to enable them (I didn't enable any mods and they appeared in my game just without any problem).

![missions](https://user-images.githubusercontent.com/9843181/78417647-787c2400-7634-11ea-92f7-4513807131ee.png)

If you subscribe a mod that contains 'Addons' directory then it should appear in launcher
https://steamcommunity.com/workshop/filedetails/?id=450814997 - you can try testing it with this mod :)

**Comment by Crafol** [comment]
Hahaha I feel like an idiot. :( Hahahaha
Downloading and tested ...

**Comment by Crafol** [comment]
Thk!
![Captura de pantalla de 2020-04-04 01-33-23](https://user-images.githubusercontent.com/3323764/78418639-6094a800-7614-11ea-98ac-9cd8b88412bf.png)

**Comment by muttleyxd** [comment]
> Hahaha I feel like an idiot. :( Hahahaha

I guess this feature is a little confusing :D
Possibly I could display mission mods, even though they wouldn't do anything.

It's weird that it shows 'cannot read name' for 'CUP Terrains - Core'. I guess we have another bug here

Anyway, good that we've got it working for you!
