### ISSUE TITLE
downloading/installing issues

### ISSUE THREAD

**Issue by mulltonne42** [muttleyxd/arma3-unix-launcher#83]
Since installing it over the ubuntu software installer didnt work, i tried installing it via the source code.
but this error appears:

 Err:1 http://de.archive.ubuntu.com/ubuntu disco/main amd64 cmake amd64 3.13.4-1
   404  Not Found [IP: 141.30.62.24 80]
 E: Failed to fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cmak/cmake_3.13.4-1_amd64.deb  404  Not Found [IP: 141.30.62.24 80]
 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I am rather new to linux and both options the console told me didnt work, please help :(

**Comment by muttleyxd** [comment]
Probably your mirrors are out of date, try installing like that

```shell
sudo apt update
sudo apt install libqt5widgets5 libqt5svg5
wget https://github.com/muttleyxd/arma3-unix-launcher/releases/download/commit-170/arma3-unix-launcher-170.ca3b5df-ubuntu-18.04-amd64.deb
sudo dpkg -i arma3-unix-launcher-170.ca3b5df-ubuntu-18.04-amd64.deb
```

and then run it with:
```shell
arma3-unix-launcher
```

**Comment by mulltonne42** [comment]
Thanks alot it worked :D
