### ISSUE TITLE
Custom Proton breaks launcher

### ISSUE THREAD

**Issue by droidmahn** [muttleyxd/arma3-unix-launcher#85]
Game wont launch with custom proton (5.0.4-GE)
env: ‘/home/USER/.local/share/Steam/steamapps/common//proton’: No such file or directory

**Comment by muttleyxd** [comment]
For now launcher doesn't support detecting custom Proton installations, will add it in few days.

**Comment by muttleyxd** [comment]
Fixed with fe51564

Feel free to reopen the issue if the issue persists :)
