### ISSUE TITLE
dependencies missing when installing from AUR package

### ISSUE THREAD

**Issue by nojusr** [muttleyxd/arma3-unix-launcher#86]
After running `$ yay -S arma3-unix-launcher`, waiting for it to finish installing, and then running it from the command line I get this:
```
[user@machine]: ~>$ arma3-unix-launcher
arma3-unix-launcher: error while loading shared libraries: libpugixml.so.1: cannot open shared object file: No such file or directory
```
This isn't a very high priority issue as i can just install the dependencies separately but this wouldn't be too hard to fix either.

**Comment by muttleyxd** [comment]
I've updated AUR package, should be fine now. Thanks for reporting :+1:

Feel free to reopen if issue persists
