### ISSUE TITLE
Implement UI Mod Ordering

### ISSUE THREAD

**Issue by Spartan322** [muttleyxd/arma3-unix-launcher#94]
Mod order is a vitally important aspect of loading mods, (specifically dependent mods or mods that override other mods) and it doesn't appear that this launcher actually supports reordering mods, it appears to sort mods by their name, which is problematic with multiple big mods that rely on CBA.

**Comment by muttleyxd** [comment]
I'll have to think how to implement reordering mods in UI. After that it'll be pretty trivial fixes.

Consider it work-in-progress now

**Comment by muttleyxd** [comment]
Closed by #143

Feel free to reopen if issue persists.
